// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module cnn_stream_accel_max_pooling (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        conv_to_pool_stream_V_dout,
        conv_to_pool_stream_V_empty_n,
        conv_to_pool_stream_V_read,
        pool_to_flat_stream_V_din,
        pool_to_flat_stream_V_full_n,
        pool_to_flat_stream_V_write
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_pp0_stage0 = 6'd2;
parameter    ap_ST_fsm_pp0_stage1 = 6'd4;
parameter    ap_ST_fsm_pp0_stage2 = 6'd8;
parameter    ap_ST_fsm_pp0_stage3 = 6'd16;
parameter    ap_ST_fsm_state14 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] conv_to_pool_stream_V_dout;
input   conv_to_pool_stream_V_empty_n;
output   conv_to_pool_stream_V_read;
output  [31:0] pool_to_flat_stream_V_din;
input   pool_to_flat_stream_V_full_n;
output   pool_to_flat_stream_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg conv_to_pool_stream_V_read;
reg pool_to_flat_stream_V_write;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    conv_to_pool_stream_V_blk_n;
wire    ap_CS_fsm_pp0_stage1;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage1;
reg   [0:0] icmp_ln15_reg_408;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg    pool_to_flat_stream_V_blk_n;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] icmp_ln15_reg_408_pp0_iter2_reg;
reg   [7:0] indvar_flatten_reg_67;
wire   [7:0] add_ln15_fu_83_p2;
reg   [7:0] add_ln15_reg_403;
wire    ap_block_state2_pp0_stage0_iter0;
reg    ap_block_state6_pp0_stage0_iter1;
wire    ap_block_state10_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln15_fu_89_p2;
reg   [0:0] icmp_ln15_reg_408_pp0_iter1_reg;
reg   [31:0] conv_to_pool_stream_V_read_reg_412;
reg    ap_block_state3_pp0_stage1_iter0;
wire    ap_block_state7_pp0_stage1_iter1;
wire    ap_block_state11_pp0_stage1_iter2;
reg    ap_block_pp0_stage1_11001;
reg   [31:0] conv_to_pool_stream_V_read_1_reg_419;
reg    ap_block_state4_pp0_stage2_iter0;
wire    ap_block_state8_pp0_stage2_iter1;
wire    ap_block_state12_pp0_stage2_iter2;
reg    ap_block_pp0_stage2_11001;
wire   [0:0] icmp_ln28_fu_112_p2;
reg   [0:0] icmp_ln28_reg_426;
reg    ap_block_state5_pp0_stage3_iter0;
wire    ap_block_state9_pp0_stage3_iter1;
reg    ap_block_state13_pp0_stage3_iter2;
reg    ap_block_pp0_stage3_11001;
wire   [0:0] icmp_ln28_1_fu_118_p2;
reg   [0:0] icmp_ln28_1_reg_431;
wire   [0:0] grp_fu_78_p2;
reg   [0:0] tmp_1_reg_436;
reg   [31:0] conv_to_pool_stream_V_read_2_reg_441;
reg   [31:0] conv_to_pool_stream_V_read_2_reg_441_pp0_iter1_reg;
wire   [31:0] select_ln28_fu_133_p3;
reg   [31:0] select_ln28_reg_448;
reg   [31:0] conv_to_pool_stream_V_read_3_reg_455;
reg   [31:0] conv_to_pool_stream_V_read_3_reg_455_pp0_iter2_reg;
wire   [31:0] select_ln28_1_fu_223_p3;
reg   [31:0] select_ln28_1_reg_462;
wire   [31:0] select_ln28_2_fu_311_p3;
reg   [31:0] select_ln28_2_reg_469;
wire   [0:0] icmp_ln28_10_fu_334_p2;
reg   [0:0] icmp_ln28_10_reg_476;
wire   [0:0] icmp_ln28_11_fu_340_p2;
reg   [0:0] icmp_ln28_11_reg_481;
wire   [31:0] select_ln28_3_fu_397_p3;
reg   [31:0] select_ln28_3_reg_486;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_block_pp0_stage3_subdone;
reg   [7:0] ap_phi_mux_indvar_flatten_phi_fu_71_p4;
reg    ap_block_pp0_stage3_01001;
reg   [31:0] grp_fu_78_p0;
reg   [31:0] grp_fu_78_p1;
wire   [31:0] bitcast_ln28_fu_95_p1;
wire   [7:0] tmp_fu_98_p4;
wire   [22:0] trunc_ln28_fu_108_p1;
wire   [0:0] or_ln28_fu_124_p2;
wire   [0:0] and_ln28_fu_128_p2;
wire   [31:0] bitcast_ln28_1_fu_141_p1;
wire   [31:0] bitcast_ln28_2_fu_158_p1;
wire   [7:0] tmp_2_fu_144_p4;
wire   [22:0] trunc_ln28_1_fu_154_p1;
wire   [0:0] icmp_ln28_3_fu_181_p2;
wire   [0:0] icmp_ln28_2_fu_175_p2;
wire   [7:0] tmp_3_fu_161_p4;
wire   [22:0] trunc_ln28_2_fu_171_p1;
wire   [0:0] icmp_ln28_5_fu_199_p2;
wire   [0:0] icmp_ln28_4_fu_193_p2;
wire   [0:0] or_ln28_1_fu_187_p2;
wire   [0:0] or_ln28_2_fu_205_p2;
wire   [0:0] and_ln28_1_fu_211_p2;
wire   [0:0] and_ln28_2_fu_217_p2;
wire   [31:0] bitcast_ln28_3_fu_229_p1;
wire   [31:0] bitcast_ln28_4_fu_246_p1;
wire   [7:0] tmp_5_fu_232_p4;
wire   [22:0] trunc_ln28_3_fu_242_p1;
wire   [0:0] icmp_ln28_7_fu_269_p2;
wire   [0:0] icmp_ln28_6_fu_263_p2;
wire   [7:0] tmp_6_fu_249_p4;
wire   [22:0] trunc_ln28_4_fu_259_p1;
wire   [0:0] icmp_ln28_9_fu_287_p2;
wire   [0:0] icmp_ln28_8_fu_281_p2;
wire   [0:0] or_ln28_3_fu_275_p2;
wire   [0:0] or_ln28_4_fu_293_p2;
wire   [0:0] and_ln28_3_fu_299_p2;
wire   [0:0] and_ln28_4_fu_305_p2;
wire   [31:0] bitcast_ln28_5_fu_317_p1;
wire   [7:0] tmp_8_fu_320_p4;
wire   [22:0] trunc_ln28_5_fu_330_p1;
wire   [31:0] bitcast_ln28_6_fu_346_p1;
wire   [7:0] tmp_9_fu_349_p4;
wire   [22:0] trunc_ln28_6_fu_359_p1;
wire   [0:0] icmp_ln28_13_fu_373_p2;
wire   [0:0] icmp_ln28_12_fu_367_p2;
wire   [0:0] or_ln28_5_fu_363_p2;
wire   [0:0] or_ln28_6_fu_379_p2;
wire   [0:0] and_ln28_5_fu_385_p2;
wire   [0:0] and_ln28_6_fu_391_p2;
reg    grp_fu_78_ce;
reg    ap_block_pp0_stage2_00001;
reg    ap_block_pp0_stage0_00001;
reg    ap_block_pp0_stage3_00001;
reg    ap_block_pp0_stage1_00001;
wire    ap_CS_fsm_state14;
reg   [5:0] ap_NS_fsm;
reg    ap_block_pp0_stage1_subdone;
reg    ap_block_pp0_stage2_subdone;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
end

cnn_stream_accel_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U63(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_78_p0),
    .din1(grp_fu_78_p1),
    .ce(grp_fu_78_ce),
    .opcode(5'd2),
    .dout(grp_fu_78_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln15_reg_408 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten_reg_67 <= add_ln15_reg_403;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        indvar_flatten_reg_67 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln15_reg_403 <= add_ln15_fu_83_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln15_reg_408 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        conv_to_pool_stream_V_read_1_reg_419 <= conv_to_pool_stream_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln15_reg_408 == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        conv_to_pool_stream_V_read_2_reg_441 <= conv_to_pool_stream_V_dout;
        tmp_1_reg_436 <= grp_fu_78_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        conv_to_pool_stream_V_read_2_reg_441_pp0_iter1_reg <= conv_to_pool_stream_V_read_2_reg_441;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln15_reg_408 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_to_pool_stream_V_read_3_reg_455 <= conv_to_pool_stream_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_to_pool_stream_V_read_3_reg_455_pp0_iter2_reg <= conv_to_pool_stream_V_read_3_reg_455;
        icmp_ln15_reg_408 <= icmp_ln15_fu_89_p2;
        icmp_ln15_reg_408_pp0_iter1_reg <= icmp_ln15_reg_408;
        icmp_ln15_reg_408_pp0_iter2_reg <= icmp_ln15_reg_408_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln15_reg_408 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        conv_to_pool_stream_V_read_reg_412 <= conv_to_pool_stream_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln15_reg_408_pp0_iter1_reg == 1'd0))) begin
        icmp_ln28_10_reg_476 <= icmp_ln28_10_fu_334_p2;
        icmp_ln28_11_reg_481 <= icmp_ln28_11_fu_340_p2;
        select_ln28_2_reg_469 <= select_ln28_2_fu_311_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln15_reg_408 == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        icmp_ln28_1_reg_431 <= icmp_ln28_1_fu_118_p2;
        icmp_ln28_reg_426 <= icmp_ln28_fu_112_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln15_reg_408_pp0_iter1_reg == 1'd0))) begin
        select_ln28_1_reg_462 <= select_ln28_1_fu_223_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln15_reg_408_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        select_ln28_3_reg_486 <= select_ln28_3_fu_397_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln15_reg_408 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        select_ln28_reg_448 <= select_ln28_fu_133_p3;
    end
end

always @ (*) begin
    if ((icmp_ln15_fu_89_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln15_reg_408 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_indvar_flatten_phi_fu_71_p4 = add_ln15_reg_403;
    end else begin
        ap_phi_mux_indvar_flatten_phi_fu_71_p4 = indvar_flatten_reg_67;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln15_reg_408 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln15_reg_408 == 1'd0) & (1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((icmp_ln15_reg_408 == 1'd0) & (1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((icmp_ln15_reg_408 == 1'd0) & (1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        conv_to_pool_stream_V_blk_n = conv_to_pool_stream_V_empty_n;
    end else begin
        conv_to_pool_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln15_reg_408 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln15_reg_408 == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((icmp_ln15_reg_408 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((icmp_ln15_reg_408 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        conv_to_pool_stream_V_read = 1'b1;
    end else begin
        conv_to_pool_stream_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_78_ce = 1'b1;
    end else begin
        grp_fu_78_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_78_p0 = conv_to_pool_stream_V_read_3_reg_455_pp0_iter2_reg;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_78_p0 = conv_to_pool_stream_V_read_2_reg_441;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_78_p0 = conv_to_pool_stream_V_read_1_reg_419;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_78_p0 = conv_to_pool_stream_V_read_reg_412;
    end else begin
        grp_fu_78_p0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_78_p1 = select_ln28_2_reg_469;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_78_p1 = select_ln28_1_reg_462;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_78_p1 = select_ln28_fu_133_p3;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_78_p1 = 32'd8388608;
    end else begin
        grp_fu_78_p1 = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln15_reg_408_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        pool_to_flat_stream_V_blk_n = pool_to_flat_stream_V_full_n;
    end else begin
        pool_to_flat_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln15_reg_408_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        pool_to_flat_stream_V_write = 1'b1;
    end else begin
        pool_to_flat_stream_V_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln15_fu_89_p2 == 1'd1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln15_fu_89_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((~((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3)) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln15_fu_83_p2 = (ap_phi_mux_indvar_flatten_phi_fu_71_p4 + 8'd1);

assign and_ln28_1_fu_211_p2 = (or_ln28_2_fu_205_p2 & or_ln28_1_fu_187_p2);

assign and_ln28_2_fu_217_p2 = (grp_fu_78_p2 & and_ln28_1_fu_211_p2);

assign and_ln28_3_fu_299_p2 = (or_ln28_4_fu_293_p2 & or_ln28_3_fu_275_p2);

assign and_ln28_4_fu_305_p2 = (grp_fu_78_p2 & and_ln28_3_fu_299_p2);

assign and_ln28_5_fu_385_p2 = (or_ln28_6_fu_379_p2 & or_ln28_5_fu_363_p2);

assign and_ln28_6_fu_391_p2 = (grp_fu_78_p2 & and_ln28_5_fu_385_p2);

assign and_ln28_fu_128_p2 = (tmp_1_reg_436 & or_ln28_fu_124_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd5];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_00001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln15_reg_408 == 1'd0) & (conv_to_pool_stream_V_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln15_reg_408 == 1'd0) & (conv_to_pool_stream_V_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln15_reg_408 == 1'd0) & (conv_to_pool_stream_V_empty_n == 1'b0));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_00001 = ((icmp_ln15_reg_408 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (conv_to_pool_stream_V_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = ((icmp_ln15_reg_408 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (conv_to_pool_stream_V_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((icmp_ln15_reg_408 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (conv_to_pool_stream_V_empty_n == 1'b0));
end

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_00001 = ((icmp_ln15_reg_408 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (conv_to_pool_stream_V_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_pp0_stage2_11001 = ((icmp_ln15_reg_408 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (conv_to_pool_stream_V_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_pp0_stage2_subdone = ((icmp_ln15_reg_408 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (conv_to_pool_stream_V_empty_n == 1'b0));
end

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_00001 = (((icmp_ln15_reg_408_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (pool_to_flat_stream_V_full_n == 1'b0)) | ((icmp_ln15_reg_408 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (conv_to_pool_stream_V_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage3_01001 = (((icmp_ln15_reg_408_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (pool_to_flat_stream_V_full_n == 1'b0)) | ((icmp_ln15_reg_408 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (conv_to_pool_stream_V_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage3_11001 = (((icmp_ln15_reg_408_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (pool_to_flat_stream_V_full_n == 1'b0)) | ((icmp_ln15_reg_408 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (conv_to_pool_stream_V_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage3_subdone = (((icmp_ln15_reg_408_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (pool_to_flat_stream_V_full_n == 1'b0)) | ((icmp_ln15_reg_408 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (conv_to_pool_stream_V_empty_n == 1'b0)));
end

assign ap_block_state10_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage2_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state13_pp0_stage3_iter2 = ((icmp_ln15_reg_408_pp0_iter2_reg == 1'd0) & (pool_to_flat_stream_V_full_n == 1'b0));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage1_iter0 = ((icmp_ln15_reg_408 == 1'd0) & (conv_to_pool_stream_V_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state4_pp0_stage2_iter0 = ((icmp_ln15_reg_408 == 1'd0) & (conv_to_pool_stream_V_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state5_pp0_stage3_iter0 = ((icmp_ln15_reg_408 == 1'd0) & (conv_to_pool_stream_V_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state6_pp0_stage0_iter1 = ((icmp_ln15_reg_408 == 1'd0) & (conv_to_pool_stream_V_empty_n == 1'b0));
end

assign ap_block_state7_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage3_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign bitcast_ln28_1_fu_141_p1 = conv_to_pool_stream_V_read_1_reg_419;

assign bitcast_ln28_2_fu_158_p1 = select_ln28_reg_448;

assign bitcast_ln28_3_fu_229_p1 = conv_to_pool_stream_V_read_2_reg_441_pp0_iter1_reg;

assign bitcast_ln28_4_fu_246_p1 = select_ln28_1_reg_462;

assign bitcast_ln28_5_fu_317_p1 = conv_to_pool_stream_V_read_3_reg_455;

assign bitcast_ln28_6_fu_346_p1 = select_ln28_2_reg_469;

assign bitcast_ln28_fu_95_p1 = conv_to_pool_stream_V_read_reg_412;

assign icmp_ln15_fu_89_p2 = ((ap_phi_mux_indvar_flatten_phi_fu_71_p4 == 8'd196) ? 1'b1 : 1'b0);

assign icmp_ln28_10_fu_334_p2 = ((tmp_8_fu_320_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln28_11_fu_340_p2 = ((trunc_ln28_5_fu_330_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln28_12_fu_367_p2 = ((tmp_9_fu_349_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln28_13_fu_373_p2 = ((trunc_ln28_6_fu_359_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln28_1_fu_118_p2 = ((trunc_ln28_fu_108_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln28_2_fu_175_p2 = ((tmp_2_fu_144_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln28_3_fu_181_p2 = ((trunc_ln28_1_fu_154_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln28_4_fu_193_p2 = ((tmp_3_fu_161_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln28_5_fu_199_p2 = ((trunc_ln28_2_fu_171_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln28_6_fu_263_p2 = ((tmp_5_fu_232_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln28_7_fu_269_p2 = ((trunc_ln28_3_fu_242_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln28_8_fu_281_p2 = ((tmp_6_fu_249_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln28_9_fu_287_p2 = ((trunc_ln28_4_fu_259_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln28_fu_112_p2 = ((tmp_fu_98_p4 != 8'd255) ? 1'b1 : 1'b0);

assign or_ln28_1_fu_187_p2 = (icmp_ln28_3_fu_181_p2 | icmp_ln28_2_fu_175_p2);

assign or_ln28_2_fu_205_p2 = (icmp_ln28_5_fu_199_p2 | icmp_ln28_4_fu_193_p2);

assign or_ln28_3_fu_275_p2 = (icmp_ln28_7_fu_269_p2 | icmp_ln28_6_fu_263_p2);

assign or_ln28_4_fu_293_p2 = (icmp_ln28_9_fu_287_p2 | icmp_ln28_8_fu_281_p2);

assign or_ln28_5_fu_363_p2 = (icmp_ln28_11_reg_481 | icmp_ln28_10_reg_476);

assign or_ln28_6_fu_379_p2 = (icmp_ln28_13_fu_373_p2 | icmp_ln28_12_fu_367_p2);

assign or_ln28_fu_124_p2 = (icmp_ln28_reg_426 | icmp_ln28_1_reg_431);

assign pool_to_flat_stream_V_din = select_ln28_3_reg_486;

assign select_ln28_1_fu_223_p3 = ((and_ln28_2_fu_217_p2[0:0] == 1'b1) ? conv_to_pool_stream_V_read_1_reg_419 : select_ln28_reg_448);

assign select_ln28_2_fu_311_p3 = ((and_ln28_4_fu_305_p2[0:0] == 1'b1) ? conv_to_pool_stream_V_read_2_reg_441_pp0_iter1_reg : select_ln28_1_reg_462);

assign select_ln28_3_fu_397_p3 = ((and_ln28_6_fu_391_p2[0:0] == 1'b1) ? conv_to_pool_stream_V_read_3_reg_455_pp0_iter2_reg : select_ln28_2_reg_469);

assign select_ln28_fu_133_p3 = ((and_ln28_fu_128_p2[0:0] == 1'b1) ? conv_to_pool_stream_V_read_reg_412 : 32'd8388608);

assign tmp_2_fu_144_p4 = {{bitcast_ln28_1_fu_141_p1[30:23]}};

assign tmp_3_fu_161_p4 = {{bitcast_ln28_2_fu_158_p1[30:23]}};

assign tmp_5_fu_232_p4 = {{bitcast_ln28_3_fu_229_p1[30:23]}};

assign tmp_6_fu_249_p4 = {{bitcast_ln28_4_fu_246_p1[30:23]}};

assign tmp_8_fu_320_p4 = {{bitcast_ln28_5_fu_317_p1[30:23]}};

assign tmp_9_fu_349_p4 = {{bitcast_ln28_6_fu_346_p1[30:23]}};

assign tmp_fu_98_p4 = {{bitcast_ln28_fu_95_p1[30:23]}};

assign trunc_ln28_1_fu_154_p1 = bitcast_ln28_1_fu_141_p1[22:0];

assign trunc_ln28_2_fu_171_p1 = bitcast_ln28_2_fu_158_p1[22:0];

assign trunc_ln28_3_fu_242_p1 = bitcast_ln28_3_fu_229_p1[22:0];

assign trunc_ln28_4_fu_259_p1 = bitcast_ln28_4_fu_246_p1[22:0];

assign trunc_ln28_5_fu_330_p1 = bitcast_ln28_5_fu_317_p1[22:0];

assign trunc_ln28_6_fu_359_p1 = bitcast_ln28_6_fu_346_p1[22:0];

assign trunc_ln28_fu_108_p1 = bitcast_ln28_fu_95_p1[22:0];

endmodule //cnn_stream_accel_max_pooling
