-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cnn_stream_accel_max_pooling is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    conv_to_pool_stream_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_to_pool_stream_V_empty_n : IN STD_LOGIC;
    conv_to_pool_stream_V_read : OUT STD_LOGIC;
    pool_to_flat_stream_V_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    pool_to_flat_stream_V_full_n : IN STD_LOGIC;
    pool_to_flat_stream_V_write : OUT STD_LOGIC );
end;


architecture behav of cnn_stream_accel_max_pooling is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_800000 : STD_LOGIC_VECTOR (31 downto 0) := "00000000100000000000000000000000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv8_C4 : STD_LOGIC_VECTOR (7 downto 0) := "11000100";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal conv_to_pool_stream_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal icmp_ln15_reg_408 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage3 : signal is "none";
    signal ap_block_pp0_stage3 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal pool_to_flat_stream_V_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal icmp_ln15_reg_408_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal indvar_flatten_reg_67 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln15_fu_83_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln15_reg_403 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln15_fu_89_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln15_reg_408_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal conv_to_pool_stream_V_read_reg_412 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state3_pp0_stage1_iter0 : BOOLEAN;
    signal ap_block_state7_pp0_stage1_iter1 : BOOLEAN;
    signal ap_block_state11_pp0_stage1_iter2 : BOOLEAN;
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal conv_to_pool_stream_V_read_1_reg_419 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state4_pp0_stage2_iter0 : BOOLEAN;
    signal ap_block_state8_pp0_stage2_iter1 : BOOLEAN;
    signal ap_block_state12_pp0_stage2_iter2 : BOOLEAN;
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal icmp_ln28_fu_112_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln28_reg_426 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state5_pp0_stage3_iter0 : BOOLEAN;
    signal ap_block_state9_pp0_stage3_iter1 : BOOLEAN;
    signal ap_block_state13_pp0_stage3_iter2 : BOOLEAN;
    signal ap_block_pp0_stage3_11001 : BOOLEAN;
    signal icmp_ln28_1_fu_118_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln28_1_reg_431 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_78_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_reg_436 : STD_LOGIC_VECTOR (0 downto 0);
    signal conv_to_pool_stream_V_read_2_reg_441 : STD_LOGIC_VECTOR (31 downto 0);
    signal conv_to_pool_stream_V_read_2_reg_441_pp0_iter1_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln28_fu_133_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln28_reg_448 : STD_LOGIC_VECTOR (31 downto 0);
    signal conv_to_pool_stream_V_read_3_reg_455 : STD_LOGIC_VECTOR (31 downto 0);
    signal conv_to_pool_stream_V_read_3_reg_455_pp0_iter2_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln28_1_fu_223_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln28_1_reg_462 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln28_2_fu_311_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln28_2_reg_469 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln28_10_fu_334_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln28_10_reg_476 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln28_11_fu_340_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln28_11_reg_481 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln28_3_fu_397_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln28_3_reg_486 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state2 : STD_LOGIC;
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal ap_phi_mux_indvar_flatten_phi_fu_71_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage3_01001 : BOOLEAN;
    signal grp_fu_78_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_78_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln28_fu_95_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_98_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln28_fu_108_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal or_ln28_fu_124_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln28_fu_128_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln28_1_fu_141_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln28_2_fu_158_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_144_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln28_1_fu_154_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln28_3_fu_181_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln28_2_fu_175_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_161_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln28_2_fu_171_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln28_5_fu_199_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln28_4_fu_193_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln28_1_fu_187_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln28_2_fu_205_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln28_1_fu_211_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln28_2_fu_217_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln28_3_fu_229_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln28_4_fu_246_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_5_fu_232_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln28_3_fu_242_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln28_7_fu_269_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln28_6_fu_263_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_fu_249_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln28_4_fu_259_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln28_9_fu_287_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln28_8_fu_281_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln28_3_fu_275_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln28_4_fu_293_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln28_3_fu_299_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln28_4_fu_305_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln28_5_fu_317_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_8_fu_320_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln28_5_fu_330_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal bitcast_ln28_6_fu_346_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_9_fu_349_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln28_6_fu_359_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln28_13_fu_373_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln28_12_fu_367_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln28_5_fu_363_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln28_6_fu_379_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln28_5_fu_385_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln28_6_fu_391_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_78_ce : STD_LOGIC;
    signal ap_block_pp0_stage2_00001 : BOOLEAN;
    signal ap_block_pp0_stage0_00001 : BOOLEAN;
    signal ap_block_pp0_stage3_00001 : BOOLEAN;
    signal ap_block_pp0_stage1_00001 : BOOLEAN;
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component cnn_stream_accel_fcmp_32ns_32ns_1_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;



begin
    fcmp_32ns_32ns_1_2_no_dsp_1_U63 : component cnn_stream_accel_fcmp_32ns_32ns_1_2_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_78_p0,
        din1 => grp_fu_78_p1,
        ce => grp_fu_78_ce,
        opcode => ap_const_lv5_2,
        dout => grp_fu_78_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten_reg_67_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln15_reg_408 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                indvar_flatten_reg_67 <= add_ln15_reg_403;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                indvar_flatten_reg_67 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln15_reg_403 <= add_ln15_fu_83_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln15_reg_408 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                conv_to_pool_stream_V_read_1_reg_419 <= conv_to_pool_stream_V_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln15_reg_408 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                conv_to_pool_stream_V_read_2_reg_441 <= conv_to_pool_stream_V_dout;
                tmp_1_reg_436 <= grp_fu_78_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                conv_to_pool_stream_V_read_2_reg_441_pp0_iter1_reg <= conv_to_pool_stream_V_read_2_reg_441;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln15_reg_408 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                conv_to_pool_stream_V_read_3_reg_455 <= conv_to_pool_stream_V_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                conv_to_pool_stream_V_read_3_reg_455_pp0_iter2_reg <= conv_to_pool_stream_V_read_3_reg_455;
                icmp_ln15_reg_408 <= icmp_ln15_fu_89_p2;
                icmp_ln15_reg_408_pp0_iter1_reg <= icmp_ln15_reg_408;
                icmp_ln15_reg_408_pp0_iter2_reg <= icmp_ln15_reg_408_pp0_iter1_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln15_reg_408 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                conv_to_pool_stream_V_read_reg_412 <= conv_to_pool_stream_V_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln15_reg_408_pp0_iter1_reg = ap_const_lv1_0))) then
                icmp_ln28_10_reg_476 <= icmp_ln28_10_fu_334_p2;
                icmp_ln28_11_reg_481 <= icmp_ln28_11_fu_340_p2;
                select_ln28_2_reg_469 <= select_ln28_2_fu_311_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln15_reg_408 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                icmp_ln28_1_reg_431 <= icmp_ln28_1_fu_118_p2;
                icmp_ln28_reg_426 <= icmp_ln28_fu_112_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln15_reg_408_pp0_iter1_reg = ap_const_lv1_0))) then
                select_ln28_1_reg_462 <= select_ln28_1_fu_223_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln15_reg_408_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                select_ln28_3_reg_486 <= select_ln28_3_fu_397_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln15_reg_408 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                select_ln28_reg_448 <= select_ln28_fu_133_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage3, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, icmp_ln15_fu_89_p2, ap_block_pp0_stage0_subdone, ap_block_pp0_stage3_subdone, ap_block_pp0_stage1_subdone, ap_block_pp0_stage2_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln15_fu_89_p2 = ap_const_lv1_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln15_fu_89_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state14;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if ((not(((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                    ap_NS_fsm <= ap_ST_fsm_state14;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    add_ln15_fu_83_p2 <= std_logic_vector(unsigned(ap_phi_mux_indvar_flatten_phi_fu_71_p4) + unsigned(ap_const_lv8_1));
    and_ln28_1_fu_211_p2 <= (or_ln28_2_fu_205_p2 and or_ln28_1_fu_187_p2);
    and_ln28_2_fu_217_p2 <= (grp_fu_78_p2 and and_ln28_1_fu_211_p2);
    and_ln28_3_fu_299_p2 <= (or_ln28_4_fu_293_p2 and or_ln28_3_fu_275_p2);
    and_ln28_4_fu_305_p2 <= (grp_fu_78_p2 and and_ln28_3_fu_299_p2);
    and_ln28_5_fu_385_p2 <= (or_ln28_6_fu_379_p2 and or_ln28_5_fu_363_p2);
    and_ln28_6_fu_391_p2 <= (grp_fu_78_p2 and and_ln28_5_fu_385_p2);
    and_ln28_fu_128_p2 <= (tmp_1_reg_436 and or_ln28_fu_124_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(3);
    ap_CS_fsm_pp0_stage3 <= ap_CS_fsm(4);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state14 <= ap_CS_fsm(5);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_00001_assign_proc : process(conv_to_pool_stream_V_empty_n, icmp_ln15_reg_408, ap_enable_reg_pp0_iter1)
    begin
                ap_block_pp0_stage0_00001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln15_reg_408 = ap_const_lv1_0) and (conv_to_pool_stream_V_empty_n = ap_const_logic_0));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(conv_to_pool_stream_V_empty_n, icmp_ln15_reg_408, ap_enable_reg_pp0_iter1)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln15_reg_408 = ap_const_lv1_0) and (conv_to_pool_stream_V_empty_n = ap_const_logic_0));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(conv_to_pool_stream_V_empty_n, icmp_ln15_reg_408, ap_enable_reg_pp0_iter1)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln15_reg_408 = ap_const_lv1_0) and (conv_to_pool_stream_V_empty_n = ap_const_logic_0));
    end process;

        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_00001_assign_proc : process(conv_to_pool_stream_V_empty_n, ap_enable_reg_pp0_iter0, icmp_ln15_reg_408)
    begin
                ap_block_pp0_stage1_00001 <= ((icmp_ln15_reg_408 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (conv_to_pool_stream_V_empty_n = ap_const_logic_0));
    end process;


    ap_block_pp0_stage1_11001_assign_proc : process(conv_to_pool_stream_V_empty_n, ap_enable_reg_pp0_iter0, icmp_ln15_reg_408)
    begin
                ap_block_pp0_stage1_11001 <= ((icmp_ln15_reg_408 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (conv_to_pool_stream_V_empty_n = ap_const_logic_0));
    end process;


    ap_block_pp0_stage1_subdone_assign_proc : process(conv_to_pool_stream_V_empty_n, ap_enable_reg_pp0_iter0, icmp_ln15_reg_408)
    begin
                ap_block_pp0_stage1_subdone <= ((icmp_ln15_reg_408 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (conv_to_pool_stream_V_empty_n = ap_const_logic_0));
    end process;

        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_00001_assign_proc : process(conv_to_pool_stream_V_empty_n, ap_enable_reg_pp0_iter0, icmp_ln15_reg_408)
    begin
                ap_block_pp0_stage2_00001 <= ((icmp_ln15_reg_408 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (conv_to_pool_stream_V_empty_n = ap_const_logic_0));
    end process;


    ap_block_pp0_stage2_11001_assign_proc : process(conv_to_pool_stream_V_empty_n, ap_enable_reg_pp0_iter0, icmp_ln15_reg_408)
    begin
                ap_block_pp0_stage2_11001 <= ((icmp_ln15_reg_408 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (conv_to_pool_stream_V_empty_n = ap_const_logic_0));
    end process;


    ap_block_pp0_stage2_subdone_assign_proc : process(conv_to_pool_stream_V_empty_n, ap_enable_reg_pp0_iter0, icmp_ln15_reg_408)
    begin
                ap_block_pp0_stage2_subdone <= ((icmp_ln15_reg_408 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (conv_to_pool_stream_V_empty_n = ap_const_logic_0));
    end process;

        ap_block_pp0_stage3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage3_00001_assign_proc : process(conv_to_pool_stream_V_empty_n, pool_to_flat_stream_V_full_n, ap_enable_reg_pp0_iter0, icmp_ln15_reg_408, ap_enable_reg_pp0_iter2, icmp_ln15_reg_408_pp0_iter2_reg)
    begin
                ap_block_pp0_stage3_00001 <= (((icmp_ln15_reg_408_pp0_iter2_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (pool_to_flat_stream_V_full_n = ap_const_logic_0)) or ((icmp_ln15_reg_408 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (conv_to_pool_stream_V_empty_n = ap_const_logic_0)));
    end process;


    ap_block_pp0_stage3_01001_assign_proc : process(conv_to_pool_stream_V_empty_n, pool_to_flat_stream_V_full_n, ap_enable_reg_pp0_iter0, icmp_ln15_reg_408, ap_enable_reg_pp0_iter2, icmp_ln15_reg_408_pp0_iter2_reg)
    begin
                ap_block_pp0_stage3_01001 <= (((icmp_ln15_reg_408_pp0_iter2_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (pool_to_flat_stream_V_full_n = ap_const_logic_0)) or ((icmp_ln15_reg_408 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (conv_to_pool_stream_V_empty_n = ap_const_logic_0)));
    end process;


    ap_block_pp0_stage3_11001_assign_proc : process(conv_to_pool_stream_V_empty_n, pool_to_flat_stream_V_full_n, ap_enable_reg_pp0_iter0, icmp_ln15_reg_408, ap_enable_reg_pp0_iter2, icmp_ln15_reg_408_pp0_iter2_reg)
    begin
                ap_block_pp0_stage3_11001 <= (((icmp_ln15_reg_408_pp0_iter2_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (pool_to_flat_stream_V_full_n = ap_const_logic_0)) or ((icmp_ln15_reg_408 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (conv_to_pool_stream_V_empty_n = ap_const_logic_0)));
    end process;


    ap_block_pp0_stage3_subdone_assign_proc : process(conv_to_pool_stream_V_empty_n, pool_to_flat_stream_V_full_n, ap_enable_reg_pp0_iter0, icmp_ln15_reg_408, ap_enable_reg_pp0_iter2, icmp_ln15_reg_408_pp0_iter2_reg)
    begin
                ap_block_pp0_stage3_subdone <= (((icmp_ln15_reg_408_pp0_iter2_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (pool_to_flat_stream_V_full_n = ap_const_logic_0)) or ((icmp_ln15_reg_408 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (conv_to_pool_stream_V_empty_n = ap_const_logic_0)));
    end process;

        ap_block_state10_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage1_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage2_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state13_pp0_stage3_iter2_assign_proc : process(pool_to_flat_stream_V_full_n, icmp_ln15_reg_408_pp0_iter2_reg)
    begin
                ap_block_state13_pp0_stage3_iter2 <= ((icmp_ln15_reg_408_pp0_iter2_reg = ap_const_lv1_0) and (pool_to_flat_stream_V_full_n = ap_const_logic_0));
    end process;

        ap_block_state2_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state3_pp0_stage1_iter0_assign_proc : process(conv_to_pool_stream_V_empty_n, icmp_ln15_reg_408)
    begin
                ap_block_state3_pp0_stage1_iter0 <= ((icmp_ln15_reg_408 = ap_const_lv1_0) and (conv_to_pool_stream_V_empty_n = ap_const_logic_0));
    end process;


    ap_block_state4_pp0_stage2_iter0_assign_proc : process(conv_to_pool_stream_V_empty_n, icmp_ln15_reg_408)
    begin
                ap_block_state4_pp0_stage2_iter0 <= ((icmp_ln15_reg_408 = ap_const_lv1_0) and (conv_to_pool_stream_V_empty_n = ap_const_logic_0));
    end process;


    ap_block_state5_pp0_stage3_iter0_assign_proc : process(conv_to_pool_stream_V_empty_n, icmp_ln15_reg_408)
    begin
                ap_block_state5_pp0_stage3_iter0 <= ((icmp_ln15_reg_408 = ap_const_lv1_0) and (conv_to_pool_stream_V_empty_n = ap_const_logic_0));
    end process;


    ap_block_state6_pp0_stage0_iter1_assign_proc : process(conv_to_pool_stream_V_empty_n, icmp_ln15_reg_408)
    begin
                ap_block_state6_pp0_stage0_iter1 <= ((icmp_ln15_reg_408 = ap_const_lv1_0) and (conv_to_pool_stream_V_empty_n = ap_const_logic_0));
    end process;

        ap_block_state7_pp0_stage1_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage2_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage3_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_pp0_exit_iter0_state2_assign_proc : process(icmp_ln15_fu_89_p2)
    begin
        if ((icmp_ln15_fu_89_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state14)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state14) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_indvar_flatten_phi_fu_71_p4_assign_proc : process(icmp_ln15_reg_408, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, indvar_flatten_reg_67, add_ln15_reg_403)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln15_reg_408 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_phi_mux_indvar_flatten_phi_fu_71_p4 <= add_ln15_reg_403;
        else 
            ap_phi_mux_indvar_flatten_phi_fu_71_p4 <= indvar_flatten_reg_67;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    bitcast_ln28_1_fu_141_p1 <= conv_to_pool_stream_V_read_1_reg_419;
    bitcast_ln28_2_fu_158_p1 <= select_ln28_reg_448;
    bitcast_ln28_3_fu_229_p1 <= conv_to_pool_stream_V_read_2_reg_441_pp0_iter1_reg;
    bitcast_ln28_4_fu_246_p1 <= select_ln28_1_reg_462;
    bitcast_ln28_5_fu_317_p1 <= conv_to_pool_stream_V_read_3_reg_455;
    bitcast_ln28_6_fu_346_p1 <= select_ln28_2_reg_469;
    bitcast_ln28_fu_95_p1 <= conv_to_pool_stream_V_read_reg_412;

    conv_to_pool_stream_V_blk_n_assign_proc : process(conv_to_pool_stream_V_empty_n, ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0, ap_block_pp0_stage1, icmp_ln15_reg_408, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln15_reg_408 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((icmp_ln15_reg_408 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((icmp_ln15_reg_408 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((icmp_ln15_reg_408 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            conv_to_pool_stream_V_blk_n <= conv_to_pool_stream_V_empty_n;
        else 
            conv_to_pool_stream_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    conv_to_pool_stream_V_read_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0, icmp_ln15_reg_408, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001, ap_block_pp0_stage2_11001, ap_block_pp0_stage3_11001)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln15_reg_408 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((icmp_ln15_reg_408 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((icmp_ln15_reg_408 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((icmp_ln15_reg_408 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            conv_to_pool_stream_V_read <= ap_const_logic_1;
        else 
            conv_to_pool_stream_V_read <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_78_ce_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001, ap_block_pp0_stage2_11001, ap_block_pp0_stage3_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            grp_fu_78_ce <= ap_const_logic_1;
        else 
            grp_fu_78_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_78_p0_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0, ap_block_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, ap_enable_reg_pp0_iter2, conv_to_pool_stream_V_read_reg_412, conv_to_pool_stream_V_read_1_reg_419, conv_to_pool_stream_V_read_2_reg_441, conv_to_pool_stream_V_read_3_reg_455_pp0_iter2_reg)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            grp_fu_78_p0 <= conv_to_pool_stream_V_read_3_reg_455_pp0_iter2_reg;
        elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            grp_fu_78_p0 <= conv_to_pool_stream_V_read_2_reg_441;
        elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_78_p0 <= conv_to_pool_stream_V_read_1_reg_419;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            grp_fu_78_p0 <= conv_to_pool_stream_V_read_reg_412;
        else 
            grp_fu_78_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_78_p1_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0, ap_block_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, ap_enable_reg_pp0_iter2, select_ln28_fu_133_p3, select_ln28_1_reg_462, select_ln28_2_reg_469)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            grp_fu_78_p1 <= select_ln28_2_reg_469;
        elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            grp_fu_78_p1 <= select_ln28_1_reg_462;
        elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_78_p1 <= select_ln28_fu_133_p3;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            grp_fu_78_p1 <= ap_const_lv32_800000;
        else 
            grp_fu_78_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    icmp_ln15_fu_89_p2 <= "1" when (ap_phi_mux_indvar_flatten_phi_fu_71_p4 = ap_const_lv8_C4) else "0";
    icmp_ln28_10_fu_334_p2 <= "0" when (tmp_8_fu_320_p4 = ap_const_lv8_FF) else "1";
    icmp_ln28_11_fu_340_p2 <= "1" when (trunc_ln28_5_fu_330_p1 = ap_const_lv23_0) else "0";
    icmp_ln28_12_fu_367_p2 <= "0" when (tmp_9_fu_349_p4 = ap_const_lv8_FF) else "1";
    icmp_ln28_13_fu_373_p2 <= "1" when (trunc_ln28_6_fu_359_p1 = ap_const_lv23_0) else "0";
    icmp_ln28_1_fu_118_p2 <= "1" when (trunc_ln28_fu_108_p1 = ap_const_lv23_0) else "0";
    icmp_ln28_2_fu_175_p2 <= "0" when (tmp_2_fu_144_p4 = ap_const_lv8_FF) else "1";
    icmp_ln28_3_fu_181_p2 <= "1" when (trunc_ln28_1_fu_154_p1 = ap_const_lv23_0) else "0";
    icmp_ln28_4_fu_193_p2 <= "0" when (tmp_3_fu_161_p4 = ap_const_lv8_FF) else "1";
    icmp_ln28_5_fu_199_p2 <= "1" when (trunc_ln28_2_fu_171_p1 = ap_const_lv23_0) else "0";
    icmp_ln28_6_fu_263_p2 <= "0" when (tmp_5_fu_232_p4 = ap_const_lv8_FF) else "1";
    icmp_ln28_7_fu_269_p2 <= "1" when (trunc_ln28_3_fu_242_p1 = ap_const_lv23_0) else "0";
    icmp_ln28_8_fu_281_p2 <= "0" when (tmp_6_fu_249_p4 = ap_const_lv8_FF) else "1";
    icmp_ln28_9_fu_287_p2 <= "1" when (trunc_ln28_4_fu_259_p1 = ap_const_lv23_0) else "0";
    icmp_ln28_fu_112_p2 <= "0" when (tmp_fu_98_p4 = ap_const_lv8_FF) else "1";
    or_ln28_1_fu_187_p2 <= (icmp_ln28_3_fu_181_p2 or icmp_ln28_2_fu_175_p2);
    or_ln28_2_fu_205_p2 <= (icmp_ln28_5_fu_199_p2 or icmp_ln28_4_fu_193_p2);
    or_ln28_3_fu_275_p2 <= (icmp_ln28_7_fu_269_p2 or icmp_ln28_6_fu_263_p2);
    or_ln28_4_fu_293_p2 <= (icmp_ln28_9_fu_287_p2 or icmp_ln28_8_fu_281_p2);
    or_ln28_5_fu_363_p2 <= (icmp_ln28_11_reg_481 or icmp_ln28_10_reg_476);
    or_ln28_6_fu_379_p2 <= (icmp_ln28_13_fu_373_p2 or icmp_ln28_12_fu_367_p2);
    or_ln28_fu_124_p2 <= (icmp_ln28_reg_426 or icmp_ln28_1_reg_431);

    pool_to_flat_stream_V_blk_n_assign_proc : process(pool_to_flat_stream_V_full_n, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3, ap_enable_reg_pp0_iter2, icmp_ln15_reg_408_pp0_iter2_reg)
    begin
        if (((icmp_ln15_reg_408_pp0_iter2_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            pool_to_flat_stream_V_blk_n <= pool_to_flat_stream_V_full_n;
        else 
            pool_to_flat_stream_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    pool_to_flat_stream_V_din <= select_ln28_3_reg_486;

    pool_to_flat_stream_V_write_assign_proc : process(ap_CS_fsm_pp0_stage3, ap_enable_reg_pp0_iter2, icmp_ln15_reg_408_pp0_iter2_reg, ap_block_pp0_stage3_11001)
    begin
        if (((icmp_ln15_reg_408_pp0_iter2_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            pool_to_flat_stream_V_write <= ap_const_logic_1;
        else 
            pool_to_flat_stream_V_write <= ap_const_logic_0;
        end if; 
    end process;

    select_ln28_1_fu_223_p3 <= 
        conv_to_pool_stream_V_read_1_reg_419 when (and_ln28_2_fu_217_p2(0) = '1') else 
        select_ln28_reg_448;
    select_ln28_2_fu_311_p3 <= 
        conv_to_pool_stream_V_read_2_reg_441_pp0_iter1_reg when (and_ln28_4_fu_305_p2(0) = '1') else 
        select_ln28_1_reg_462;
    select_ln28_3_fu_397_p3 <= 
        conv_to_pool_stream_V_read_3_reg_455_pp0_iter2_reg when (and_ln28_6_fu_391_p2(0) = '1') else 
        select_ln28_2_reg_469;
    select_ln28_fu_133_p3 <= 
        conv_to_pool_stream_V_read_reg_412 when (and_ln28_fu_128_p2(0) = '1') else 
        ap_const_lv32_800000;
    tmp_2_fu_144_p4 <= bitcast_ln28_1_fu_141_p1(30 downto 23);
    tmp_3_fu_161_p4 <= bitcast_ln28_2_fu_158_p1(30 downto 23);
    tmp_5_fu_232_p4 <= bitcast_ln28_3_fu_229_p1(30 downto 23);
    tmp_6_fu_249_p4 <= bitcast_ln28_4_fu_246_p1(30 downto 23);
    tmp_8_fu_320_p4 <= bitcast_ln28_5_fu_317_p1(30 downto 23);
    tmp_9_fu_349_p4 <= bitcast_ln28_6_fu_346_p1(30 downto 23);
    tmp_fu_98_p4 <= bitcast_ln28_fu_95_p1(30 downto 23);
    trunc_ln28_1_fu_154_p1 <= bitcast_ln28_1_fu_141_p1(23 - 1 downto 0);
    trunc_ln28_2_fu_171_p1 <= bitcast_ln28_2_fu_158_p1(23 - 1 downto 0);
    trunc_ln28_3_fu_242_p1 <= bitcast_ln28_3_fu_229_p1(23 - 1 downto 0);
    trunc_ln28_4_fu_259_p1 <= bitcast_ln28_4_fu_246_p1(23 - 1 downto 0);
    trunc_ln28_5_fu_330_p1 <= bitcast_ln28_5_fu_317_p1(23 - 1 downto 0);
    trunc_ln28_6_fu_359_p1 <= bitcast_ln28_6_fu_346_p1(23 - 1 downto 0);
    trunc_ln28_fu_108_p1 <= bitcast_ln28_fu_95_p1(23 - 1 downto 0);
end behav;
