// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module cnn_stream_accel_dense (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        flat_to_dense_stream_V_dout,
        flat_to_dense_stream_V_empty_n,
        flat_to_dense_stream_V_read,
        filter,
        dense_to_softmax_stream_V_din,
        dense_to_softmax_stream_V_full_n,
        dense_to_softmax_stream_V_write
);

parameter    ap_ST_fsm_state1 = 16'd1;
parameter    ap_ST_fsm_state2 = 16'd2;
parameter    ap_ST_fsm_state3 = 16'd4;
parameter    ap_ST_fsm_pp1_stage0 = 16'd8;
parameter    ap_ST_fsm_pp1_stage1 = 16'd16;
parameter    ap_ST_fsm_pp1_stage2 = 16'd32;
parameter    ap_ST_fsm_pp1_stage3 = 16'd64;
parameter    ap_ST_fsm_pp1_stage4 = 16'd128;
parameter    ap_ST_fsm_pp1_stage5 = 16'd256;
parameter    ap_ST_fsm_pp1_stage6 = 16'd512;
parameter    ap_ST_fsm_pp1_stage7 = 16'd1024;
parameter    ap_ST_fsm_pp1_stage8 = 16'd2048;
parameter    ap_ST_fsm_pp1_stage9 = 16'd4096;
parameter    ap_ST_fsm_state25 = 16'd8192;
parameter    ap_ST_fsm_pp2_stage0 = 16'd16384;
parameter    ap_ST_fsm_state28 = 16'd32768;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] flat_to_dense_stream_V_dout;
input   flat_to_dense_stream_V_empty_n;
output   flat_to_dense_stream_V_read;
input  [1:0] filter;
output  [31:0] dense_to_softmax_stream_V_din;
input   dense_to_softmax_stream_V_full_n;
output   dense_to_softmax_stream_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg flat_to_dense_stream_V_read;
reg dense_to_softmax_stream_V_write;

(* fsm_encoding = "none" *) reg   [15:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [9:0] dense_weights_0_address0;
reg    dense_weights_0_ce0;
wire   [31:0] dense_weights_0_q0;
wire   [9:0] dense_weights_1_address0;
reg    dense_weights_1_ce0;
wire   [31:0] dense_weights_1_q0;
wire   [9:0] dense_weights_2_address0;
reg    dense_weights_2_ce0;
wire   [31:0] dense_weights_2_q0;
wire   [9:0] dense_weights_3_address0;
reg    dense_weights_3_ce0;
wire   [31:0] dense_weights_3_q0;
wire   [9:0] dense_weights_4_address0;
reg    dense_weights_4_ce0;
wire   [31:0] dense_weights_4_q0;
wire   [9:0] dense_weights_5_address0;
reg    dense_weights_5_ce0;
wire   [31:0] dense_weights_5_q0;
wire   [9:0] dense_weights_6_address0;
reg    dense_weights_6_ce0;
wire   [31:0] dense_weights_6_q0;
wire   [9:0] dense_weights_7_address0;
reg    dense_weights_7_ce0;
wire   [31:0] dense_weights_7_q0;
wire   [9:0] dense_weights_8_address0;
reg    dense_weights_8_ce0;
wire   [31:0] dense_weights_8_q0;
wire   [9:0] dense_weights_9_address0;
reg    dense_weights_9_ce0;
wire   [31:0] dense_weights_9_q0;
reg    flat_to_dense_stream_V_blk_n;
wire    ap_CS_fsm_pp1_stage1;
reg    ap_enable_reg_pp1_iter0;
wire    ap_block_pp1_stage1;
reg   [0:0] icmp_ln49_reg_577;
reg    dense_to_softmax_stream_V_blk_n;
wire    ap_CS_fsm_pp2_stage0;
reg    ap_enable_reg_pp2_iter1;
wire    ap_block_pp2_stage0;
reg   [0:0] icmp_ln60_reg_741;
reg   [7:0] i_reg_357;
reg   [3:0] j_reg_368;
wire   [31:0] grp_fu_383_p2;
reg   [31:0] reg_387;
wire    ap_CS_fsm_pp1_stage5;
wire    ap_block_state9_pp1_stage5_iter0;
wire    ap_block_state19_pp1_stage5_iter1;
wire    ap_block_pp1_stage5_11001;
wire    ap_CS_fsm_pp1_stage0;
reg    ap_enable_reg_pp1_iter1;
wire    ap_block_state4_pp1_stage0_iter0;
wire    ap_block_state14_pp1_stage0_iter1;
wire    ap_block_state24_pp1_stage0_iter2;
wire    ap_block_pp1_stage0_11001;
reg   [31:0] reg_392;
wire    ap_CS_fsm_pp1_stage6;
wire    ap_block_state10_pp1_stage6_iter0;
wire    ap_block_state20_pp1_stage6_iter1;
wire    ap_block_pp1_stage6_11001;
reg    ap_block_state5_pp1_stage1_iter0;
wire    ap_block_state15_pp1_stage1_iter1;
reg    ap_block_pp1_stage1_11001;
reg   [0:0] icmp_ln49_reg_577_pp1_iter1_reg;
reg   [31:0] reg_397;
wire    ap_CS_fsm_pp1_stage7;
wire    ap_block_state11_pp1_stage7_iter0;
wire    ap_block_state21_pp1_stage7_iter1;
wire    ap_block_pp1_stage7_11001;
wire    ap_CS_fsm_pp1_stage2;
wire    ap_block_state6_pp1_stage2_iter0;
wire    ap_block_state16_pp1_stage2_iter1;
wire    ap_block_pp1_stage2_11001;
reg   [31:0] reg_402;
wire    ap_CS_fsm_pp1_stage8;
wire    ap_block_state12_pp1_stage8_iter0;
wire    ap_block_state22_pp1_stage8_iter1;
wire    ap_block_pp1_stage8_11001;
wire    ap_CS_fsm_pp1_stage3;
wire    ap_block_state7_pp1_stage3_iter0;
wire    ap_block_state17_pp1_stage3_iter1;
wire    ap_block_pp1_stage3_11001;
reg   [31:0] reg_407;
wire    ap_CS_fsm_pp1_stage9;
wire    ap_block_state13_pp1_stage9_iter0;
wire    ap_block_state23_pp1_stage9_iter1;
wire    ap_block_pp1_stage9_11001;
wire    ap_CS_fsm_pp1_stage4;
wire    ap_block_state8_pp1_stage4_iter0;
wire    ap_block_state18_pp1_stage4_iter1;
wire    ap_block_pp1_stage4_11001;
wire   [31:0] grp_fu_379_p2;
reg   [31:0] reg_412;
wire   [9:0] filter_cast_fu_418_p1;
reg   [9:0] filter_cast_reg_496;
wire   [3:0] empty_21_fu_422_p2;
wire    ap_CS_fsm_state2;
wire   [9:0] mul_fu_439_p2;
reg   [9:0] mul_reg_509;
wire    ap_CS_fsm_state3;
wire   [7:0] add_ln49_fu_444_p2;
reg   [7:0] add_ln49_reg_572;
wire   [0:0] icmp_ln49_fu_450_p2;
reg   [31:0] tmp_reg_631;
reg   [31:0] dense_weights_0_load_reg_636;
reg   [31:0] dense_weights_1_load_reg_641;
reg   [31:0] dense_weights_2_load_reg_646;
reg   [31:0] dense_weights_3_load_reg_651;
reg   [31:0] dense_weights_4_load_reg_656;
reg   [31:0] dense_weights_5_load_reg_661;
reg   [31:0] dense_weights_6_load_reg_666;
reg   [31:0] dense_weights_7_load_reg_671;
reg   [31:0] dense_weights_8_load_reg_676;
reg   [31:0] dense_weights_9_load_reg_681;
wire   [31:0] dense_array_q0;
reg   [31:0] dense_array_load_reg_686;
reg   [31:0] dense_array_load_1_reg_691;
reg   [31:0] dense_array_load_2_reg_696;
reg   [31:0] dense_array_load_3_reg_701;
reg   [31:0] dense_array_load_4_reg_706;
reg   [31:0] dense_array_load_5_reg_711;
reg   [31:0] dense_array_load_6_reg_716;
reg   [31:0] dense_array_load_7_reg_721;
wire   [31:0] dense_array_q1;
reg   [31:0] dense_array_load_8_reg_726;
reg   [31:0] dense_array_load_9_reg_731;
wire   [3:0] add_ln60_fu_479_p2;
reg    ap_enable_reg_pp2_iter0;
wire    ap_block_state26_pp2_stage0_iter0;
reg    ap_block_state27_pp2_stage0_iter1;
reg    ap_block_pp2_stage0_11001;
wire   [0:0] icmp_ln60_fu_485_p2;
wire    ap_block_pp1_stage0_subdone;
reg    ap_condition_pp1_exit_iter0_state4;
wire    ap_block_pp1_stage9_subdone;
reg    ap_enable_reg_pp1_iter2;
wire    ap_CS_fsm_state25;
reg    ap_block_pp2_stage0_subdone;
reg    ap_condition_pp2_exit_iter0_state26;
reg   [3:0] dense_array_address0;
reg    dense_array_ce0;
reg    dense_array_we0;
reg   [31:0] dense_array_d0;
reg   [3:0] dense_array_address1;
reg    dense_array_ce1;
reg    dense_array_we1;
reg   [3:0] empty_reg_346;
wire   [0:0] exitcond126_fu_428_p2;
reg   [7:0] ap_phi_mux_i_phi_fu_361_p4;
wire    ap_block_pp1_stage0;
wire   [63:0] p_cast_fu_434_p1;
wire   [63:0] zext_ln56_fu_465_p1;
wire   [63:0] j_cast_fu_491_p1;
reg    ap_block_pp2_stage0_01001;
wire    ap_block_pp1_stage2;
wire    ap_block_pp1_stage3;
wire    ap_block_pp1_stage4;
wire    ap_block_pp1_stage5;
wire    ap_block_pp1_stage6;
wire    ap_block_pp1_stage7;
wire    ap_block_pp1_stage8;
wire    ap_block_pp1_stage9;
reg   [31:0] grp_fu_379_p0;
reg   [31:0] grp_fu_379_p1;
reg   [31:0] grp_fu_383_p0;
wire   [1:0] mul_fu_439_p0;
wire   [8:0] mul_fu_439_p1;
wire   [9:0] i_cast_fu_456_p1;
wire   [9:0] empty_24_fu_460_p2;
reg    grp_fu_379_ce;
reg    grp_fu_383_ce;
wire    ap_CS_fsm_state28;
reg   [15:0] ap_NS_fsm;
reg    ap_block_pp1_stage1_subdone;
wire    ap_block_pp1_stage2_subdone;
wire    ap_block_pp1_stage3_subdone;
wire    ap_block_pp1_stage4_subdone;
wire    ap_block_pp1_stage5_subdone;
wire    ap_block_pp1_stage6_subdone;
wire    ap_block_pp1_stage7_subdone;
wire    ap_block_pp1_stage8_subdone;
reg    ap_idle_pp1;
wire    ap_enable_pp1;
reg    ap_idle_pp2;
wire    ap_enable_pp2;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 16'd1;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp2_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_enable_reg_pp2_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter2 = 1'b0;
end

cnn_stream_accel_dense_dense_weights_0 #(
    .DataWidth( 32 ),
    .AddressRange( 784 ),
    .AddressWidth( 10 ))
dense_weights_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dense_weights_0_address0),
    .ce0(dense_weights_0_ce0),
    .q0(dense_weights_0_q0)
);

cnn_stream_accel_dense_dense_weights_1 #(
    .DataWidth( 32 ),
    .AddressRange( 784 ),
    .AddressWidth( 10 ))
dense_weights_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dense_weights_1_address0),
    .ce0(dense_weights_1_ce0),
    .q0(dense_weights_1_q0)
);

cnn_stream_accel_dense_dense_weights_2 #(
    .DataWidth( 32 ),
    .AddressRange( 784 ),
    .AddressWidth( 10 ))
dense_weights_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dense_weights_2_address0),
    .ce0(dense_weights_2_ce0),
    .q0(dense_weights_2_q0)
);

cnn_stream_accel_dense_dense_weights_3 #(
    .DataWidth( 32 ),
    .AddressRange( 784 ),
    .AddressWidth( 10 ))
dense_weights_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dense_weights_3_address0),
    .ce0(dense_weights_3_ce0),
    .q0(dense_weights_3_q0)
);

cnn_stream_accel_dense_dense_weights_4 #(
    .DataWidth( 32 ),
    .AddressRange( 784 ),
    .AddressWidth( 10 ))
dense_weights_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dense_weights_4_address0),
    .ce0(dense_weights_4_ce0),
    .q0(dense_weights_4_q0)
);

cnn_stream_accel_dense_dense_weights_5 #(
    .DataWidth( 32 ),
    .AddressRange( 784 ),
    .AddressWidth( 10 ))
dense_weights_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dense_weights_5_address0),
    .ce0(dense_weights_5_ce0),
    .q0(dense_weights_5_q0)
);

cnn_stream_accel_dense_dense_weights_6 #(
    .DataWidth( 32 ),
    .AddressRange( 784 ),
    .AddressWidth( 10 ))
dense_weights_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dense_weights_6_address0),
    .ce0(dense_weights_6_ce0),
    .q0(dense_weights_6_q0)
);

cnn_stream_accel_dense_dense_weights_7 #(
    .DataWidth( 32 ),
    .AddressRange( 784 ),
    .AddressWidth( 10 ))
dense_weights_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dense_weights_7_address0),
    .ce0(dense_weights_7_ce0),
    .q0(dense_weights_7_q0)
);

cnn_stream_accel_dense_dense_weights_8 #(
    .DataWidth( 32 ),
    .AddressRange( 784 ),
    .AddressWidth( 10 ))
dense_weights_8_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dense_weights_8_address0),
    .ce0(dense_weights_8_ce0),
    .q0(dense_weights_8_q0)
);

cnn_stream_accel_dense_dense_weights_9 #(
    .DataWidth( 32 ),
    .AddressRange( 784 ),
    .AddressWidth( 10 ))
dense_weights_9_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dense_weights_9_address0),
    .ce0(dense_weights_9_ce0),
    .q0(dense_weights_9_q0)
);

cnn_stream_accel_dense_dense_array #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
dense_array_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dense_array_address0),
    .ce0(dense_array_ce0),
    .we0(dense_array_we0),
    .d0(dense_array_d0),
    .q0(dense_array_q0),
    .address1(dense_array_address1),
    .ce1(dense_array_ce1),
    .we1(dense_array_we1),
    .d1(reg_412),
    .q1(dense_array_q1)
);

cnn_stream_accel_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U66(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_379_p0),
    .din1(grp_fu_379_p1),
    .ce(grp_fu_379_ce),
    .dout(grp_fu_379_p2)
);

cnn_stream_accel_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U67(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_383_p0),
    .din1(tmp_reg_631),
    .ce(grp_fu_383_ce),
    .dout(grp_fu_383_p2)
);

cnn_stream_accel_mul_2ns_9ns_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 10 ))
mul_2ns_9ns_10_1_1_U68(
    .din0(mul_fu_439_p0),
    .din1(mul_fu_439_p1),
    .dout(mul_fu_439_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp1_exit_iter0_state4) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_subdone))) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp1_stage9) & (1'b0 == ap_block_pp1_stage9_subdone))) begin
            ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter2 <= 1'b0;
    end else begin
        if ((((1'b1 == ap_CS_fsm_pp1_stage9) & (1'b0 == ap_block_pp1_stage9_subdone)) | ((1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone)))) begin
            ap_enable_reg_pp1_iter2 <= ap_enable_reg_pp1_iter1;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            ap_enable_reg_pp1_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp2_exit_iter0_state26) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_subdone))) begin
            ap_enable_reg_pp2_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state25)) begin
            ap_enable_reg_pp2_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp2_exit_iter0_state26) & (1'b0 == ap_block_pp2_stage0_subdone))) begin
            ap_enable_reg_pp2_iter1 <= (1'b1 ^ ap_condition_pp2_exit_iter0_state26);
        end else if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter1 <= ap_enable_reg_pp2_iter0;
        end else if ((1'b1 == ap_CS_fsm_state25)) begin
            ap_enable_reg_pp2_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond126_fu_428_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        empty_reg_346 <= empty_21_fu_422_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        empty_reg_346 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i_reg_357 <= 8'd0;
    end else if (((1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (icmp_ln49_reg_577 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        i_reg_357 <= add_ln49_reg_572;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        j_reg_368 <= 4'd0;
    end else if (((icmp_ln60_fu_485_p2 == 1'd0) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        j_reg_368 <= add_ln60_fu_479_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        add_ln49_reg_572 <= add_ln49_fu_444_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage4) & (icmp_ln49_reg_577 == 1'd0) & (1'b0 == ap_block_pp1_stage4_11001) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        dense_array_load_1_reg_691 <= dense_array_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage5) & (icmp_ln49_reg_577 == 1'd0) & (1'b0 == ap_block_pp1_stage5_11001) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        dense_array_load_2_reg_696 <= dense_array_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage6) & (icmp_ln49_reg_577 == 1'd0) & (1'b0 == ap_block_pp1_stage6_11001) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        dense_array_load_3_reg_701 <= dense_array_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage7) & (icmp_ln49_reg_577 == 1'd0) & (1'b0 == ap_block_pp1_stage7_11001) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        dense_array_load_4_reg_706 <= dense_array_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage8) & (icmp_ln49_reg_577 == 1'd0) & (1'b0 == ap_block_pp1_stage8_11001) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        dense_array_load_5_reg_711 <= dense_array_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage9) & (icmp_ln49_reg_577 == 1'd0) & (1'b0 == ap_block_pp1_stage9_11001) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        dense_array_load_6_reg_716 <= dense_array_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (icmp_ln49_reg_577 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        dense_array_load_7_reg_721 <= dense_array_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln49_reg_577_pp1_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage1_11001))) begin
        dense_array_load_8_reg_726 <= dense_array_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln49_reg_577_pp1_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage2) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage2_11001))) begin
        dense_array_load_9_reg_731 <= dense_array_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage3) & (icmp_ln49_reg_577 == 1'd0) & (1'b0 == ap_block_pp1_stage3_11001) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        dense_array_load_reg_686 <= dense_array_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage1) & (icmp_ln49_reg_577 == 1'd0) & (1'b0 == ap_block_pp1_stage1_11001))) begin
        dense_weights_0_load_reg_636 <= dense_weights_0_q0;
        dense_weights_1_load_reg_641 <= dense_weights_1_q0;
        dense_weights_2_load_reg_646 <= dense_weights_2_q0;
        dense_weights_3_load_reg_651 <= dense_weights_3_q0;
        dense_weights_4_load_reg_656 <= dense_weights_4_q0;
        dense_weights_5_load_reg_661 <= dense_weights_5_q0;
        dense_weights_6_load_reg_666 <= dense_weights_6_q0;
        dense_weights_7_load_reg_671 <= dense_weights_7_q0;
        dense_weights_8_load_reg_676 <= dense_weights_8_q0;
        dense_weights_9_load_reg_681 <= dense_weights_9_q0;
        tmp_reg_631 <= flat_to_dense_stream_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        filter_cast_reg_496[1 : 0] <= filter_cast_fu_418_p1[1 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        icmp_ln49_reg_577 <= icmp_ln49_fu_450_p2;
        icmp_ln49_reg_577_pp1_iter1_reg <= icmp_ln49_reg_577;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        icmp_ln60_reg_741 <= icmp_ln60_fu_485_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        mul_reg_509 <= mul_fu_439_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (icmp_ln49_reg_577 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001)) | ((1'b1 == ap_CS_fsm_pp1_stage5) & (icmp_ln49_reg_577 == 1'd0) & (1'b0 == ap_block_pp1_stage5_11001) & (ap_enable_reg_pp1_iter0 == 1'b1)))) begin
        reg_387 <= grp_fu_383_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((icmp_ln49_reg_577_pp1_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp1_stage6) & (icmp_ln49_reg_577 == 1'd0) & (1'b0 == ap_block_pp1_stage6_11001) & (ap_enable_reg_pp1_iter0 == 1'b1)))) begin
        reg_392 <= grp_fu_383_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_pp1_stage7) & (icmp_ln49_reg_577 == 1'd0) & (1'b0 == ap_block_pp1_stage7_11001) & (ap_enable_reg_pp1_iter0 == 1'b1)) | ((icmp_ln49_reg_577_pp1_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage2) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage2_11001)))) begin
        reg_397 <= grp_fu_383_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_pp1_stage8) & (icmp_ln49_reg_577 == 1'd0) & (1'b0 == ap_block_pp1_stage8_11001) & (ap_enable_reg_pp1_iter0 == 1'b1)) | ((icmp_ln49_reg_577_pp1_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage3) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage3_11001)))) begin
        reg_402 <= grp_fu_383_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_pp1_stage9) & (icmp_ln49_reg_577 == 1'd0) & (1'b0 == ap_block_pp1_stage9_11001) & (ap_enable_reg_pp1_iter0 == 1'b1)) | ((icmp_ln49_reg_577_pp1_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage4) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage4_11001)))) begin
        reg_407 <= grp_fu_383_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((icmp_ln49_reg_577_pp1_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage4) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage4_11001)) | ((icmp_ln49_reg_577_pp1_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage9) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage9_11001)) | ((icmp_ln49_reg_577_pp1_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage3) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage3_11001)) | ((icmp_ln49_reg_577_pp1_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage8) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage8_11001)) | ((icmp_ln49_reg_577_pp1_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage2) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage2_11001)) | ((icmp_ln49_reg_577_pp1_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage7) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage7_11001)) | ((icmp_ln49_reg_577_pp1_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage6) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage6_11001)) | ((icmp_ln49_reg_577_pp1_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage5) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage5_11001)) | ((icmp_ln49_reg_577_pp1_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (icmp_ln49_reg_577 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        reg_412 <= grp_fu_379_p2;
    end
end

always @ (*) begin
    if ((icmp_ln49_fu_450_p2 == 1'd1)) begin
        ap_condition_pp1_exit_iter0_state4 = 1'b1;
    end else begin
        ap_condition_pp1_exit_iter0_state4 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln60_fu_485_p2 == 1'd1)) begin
        ap_condition_pp2_exit_iter0_state26 = 1'b1;
    end else begin
        ap_condition_pp2_exit_iter0_state26 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter2 == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter0 == 1'b0) & (ap_enable_reg_pp2_iter1 == 1'b0))) begin
        ap_idle_pp2 = 1'b1;
    end else begin
        ap_idle_pp2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (icmp_ln49_reg_577 == 1'd0) & (1'b0 == ap_block_pp1_stage0))) begin
        ap_phi_mux_i_phi_fu_361_p4 = add_ln49_reg_572;
    end else begin
        ap_phi_mux_i_phi_fu_361_p4 = i_reg_357;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp1_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0)) | ((1'b1 == ap_CS_fsm_pp1_stage1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage1)))) begin
        dense_array_address0 = 64'd9;
    end else if (((1'b1 == ap_CS_fsm_pp1_stage9) & (1'b0 == ap_block_pp1_stage9) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        dense_array_address0 = 64'd7;
    end else if (((1'b1 == ap_CS_fsm_pp1_stage8) & (1'b0 == ap_block_pp1_stage8) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        dense_array_address0 = 64'd6;
    end else if (((1'b1 == ap_CS_fsm_pp1_stage7) & (1'b0 == ap_block_pp1_stage7) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        dense_array_address0 = 64'd5;
    end else if (((1'b1 == ap_CS_fsm_pp1_stage6) & (1'b0 == ap_block_pp1_stage6) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        dense_array_address0 = 64'd4;
    end else if (((1'b1 == ap_CS_fsm_pp1_stage5) & (1'b0 == ap_block_pp1_stage5) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        dense_array_address0 = 64'd3;
    end else if (((1'b1 == ap_CS_fsm_pp1_stage4) & (1'b0 == ap_block_pp1_stage4) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        dense_array_address0 = 64'd2;
    end else if (((1'b1 == ap_CS_fsm_pp1_stage3) & (1'b0 == ap_block_pp1_stage3) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        dense_array_address0 = 64'd1;
    end else if (((1'b1 == ap_CS_fsm_pp1_stage2) & (1'b0 == ap_block_pp1_stage2) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        dense_array_address0 = 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        dense_array_address0 = p_cast_fu_434_p1;
    end else begin
        dense_array_address0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0))) begin
        dense_array_address1 = j_cast_fu_491_p1;
    end else if (((1'b1 == ap_CS_fsm_pp1_stage8) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage8))) begin
        dense_array_address1 = 64'd7;
    end else if (((1'b1 == ap_CS_fsm_pp1_stage7) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage7))) begin
        dense_array_address1 = 64'd6;
    end else if (((1'b1 == ap_CS_fsm_pp1_stage6) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage6))) begin
        dense_array_address1 = 64'd5;
    end else if (((1'b1 == ap_CS_fsm_pp1_stage5) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage5))) begin
        dense_array_address1 = 64'd4;
    end else if (((1'b1 == ap_CS_fsm_pp1_stage4) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage4))) begin
        dense_array_address1 = 64'd3;
    end else if (((1'b1 == ap_CS_fsm_pp1_stage3) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage3))) begin
        dense_array_address1 = 64'd2;
    end else if (((1'b1 == ap_CS_fsm_pp1_stage2) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage2))) begin
        dense_array_address1 = 64'd1;
    end else if (((1'b1 == ap_CS_fsm_pp1_stage1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage1))) begin
        dense_array_address1 = 64'd0;
    end else if ((((1'b1 == ap_CS_fsm_pp1_stage9) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage9)) | ((1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage0)))) begin
        dense_array_address1 = 64'd8;
    end else begin
        dense_array_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((ap_enable_reg_pp1_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)) | ((1'b1 == ap_CS_fsm_pp1_stage4) & (1'b0 == ap_block_pp1_stage4_11001) & (ap_enable_reg_pp1_iter0 == 1'b1)) | ((1'b1 == ap_CS_fsm_pp1_stage9) & (1'b0 == ap_block_pp1_stage9_11001) & (ap_enable_reg_pp1_iter0 == 1'b1)) | ((1'b1 == ap_CS_fsm_pp1_stage3) & (1'b0 == ap_block_pp1_stage3_11001) & (ap_enable_reg_pp1_iter0 == 1'b1)) | ((1'b1 == ap_CS_fsm_pp1_stage8) & (1'b0 == ap_block_pp1_stage8_11001) & (ap_enable_reg_pp1_iter0 == 1'b1)) | ((1'b1 == ap_CS_fsm_pp1_stage2) & (1'b0 == ap_block_pp1_stage2_11001) & (ap_enable_reg_pp1_iter0 == 1'b1)) | ((1'b1 == ap_CS_fsm_pp1_stage7) & (1'b0 == ap_block_pp1_stage7_11001) & (ap_enable_reg_pp1_iter0 == 1'b1)) | ((1'b1 == ap_CS_fsm_pp1_stage6) & (1'b0 == ap_block_pp1_stage6_11001) & (ap_enable_reg_pp1_iter0 == 1'b1)) | ((1'b1 == ap_CS_fsm_pp1_stage5) & (1'b0 == ap_block_pp1_stage5_11001) & (ap_enable_reg_pp1_iter0 == 1'b1)) | ((1'b1 == ap_CS_fsm_pp1_stage1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage1_11001)))) begin
        dense_array_ce0 = 1'b1;
    end else begin
        dense_array_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001)) | ((1'b1 == ap_CS_fsm_pp1_stage4) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage4_11001)) | ((1'b1 == ap_CS_fsm_pp1_stage9) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage9_11001)) | ((1'b1 == ap_CS_fsm_pp1_stage3) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage3_11001)) | ((1'b1 == ap_CS_fsm_pp1_stage8) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage8_11001)) | ((1'b1 == ap_CS_fsm_pp1_stage2) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage2_11001)) | ((1'b1 == ap_CS_fsm_pp1_stage7) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage7_11001)) | ((1'b1 == ap_CS_fsm_pp1_stage6) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage6_11001)) | ((1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((1'b1 == ap_CS_fsm_pp1_stage5) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage5_11001)) | ((1'b1 == ap_CS_fsm_pp1_stage1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage1_11001)))) begin
        dense_array_ce1 = 1'b1;
    end else begin
        dense_array_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0))) begin
        dense_array_d0 = reg_412;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        dense_array_d0 = 32'd0;
    end else begin
        dense_array_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp1_iter2 == 1'b1) & (icmp_ln49_reg_577_pp1_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)) | ((exitcond126_fu_428_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        dense_array_we0 = 1'b1;
    end else begin
        dense_array_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln49_reg_577_pp1_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage4) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage4_11001)) | ((icmp_ln49_reg_577_pp1_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage9) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage9_11001)) | ((icmp_ln49_reg_577_pp1_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage3) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage3_11001)) | ((icmp_ln49_reg_577_pp1_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage8) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage8_11001)) | ((icmp_ln49_reg_577_pp1_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage2) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage2_11001)) | ((icmp_ln49_reg_577_pp1_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage7) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage7_11001)) | ((icmp_ln49_reg_577_pp1_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage6) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage6_11001)) | ((icmp_ln49_reg_577_pp1_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage5) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage5_11001)) | ((icmp_ln49_reg_577_pp1_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage1_11001)))) begin
        dense_array_we1 = 1'b1;
    end else begin
        dense_array_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp2_stage0) & (icmp_ln60_reg_741 == 1'd0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b0 == ap_block_pp2_stage0))) begin
        dense_to_softmax_stream_V_blk_n = dense_to_softmax_stream_V_full_n;
    end else begin
        dense_to_softmax_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp2_stage0) & (icmp_ln60_reg_741 == 1'd0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        dense_to_softmax_stream_V_write = 1'b1;
    end else begin
        dense_to_softmax_stream_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        dense_weights_0_ce0 = 1'b1;
    end else begin
        dense_weights_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        dense_weights_1_ce0 = 1'b1;
    end else begin
        dense_weights_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        dense_weights_2_ce0 = 1'b1;
    end else begin
        dense_weights_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        dense_weights_3_ce0 = 1'b1;
    end else begin
        dense_weights_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        dense_weights_4_ce0 = 1'b1;
    end else begin
        dense_weights_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        dense_weights_5_ce0 = 1'b1;
    end else begin
        dense_weights_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        dense_weights_6_ce0 = 1'b1;
    end else begin
        dense_weights_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        dense_weights_7_ce0 = 1'b1;
    end else begin
        dense_weights_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        dense_weights_8_ce0 = 1'b1;
    end else begin
        dense_weights_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        dense_weights_9_ce0 = 1'b1;
    end else begin
        dense_weights_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage1) & (icmp_ln49_reg_577 == 1'd0) & (1'b0 == ap_block_pp1_stage1) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        flat_to_dense_stream_V_blk_n = flat_to_dense_stream_V_empty_n;
    end else begin
        flat_to_dense_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage1) & (icmp_ln49_reg_577 == 1'd0) & (1'b0 == ap_block_pp1_stage1_11001) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        flat_to_dense_stream_V_read = 1'b1;
    end else begin
        flat_to_dense_stream_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp1_stage4) & (1'b0 == ap_block_pp1_stage4_11001)) | ((1'b1 == ap_CS_fsm_pp1_stage9) & (1'b0 == ap_block_pp1_stage9_11001)) | ((1'b1 == ap_CS_fsm_pp1_stage3) & (1'b0 == ap_block_pp1_stage3_11001)) | ((1'b1 == ap_CS_fsm_pp1_stage8) & (1'b0 == ap_block_pp1_stage8_11001)) | ((1'b1 == ap_CS_fsm_pp1_stage2) & (1'b0 == ap_block_pp1_stage2_11001)) | ((1'b1 == ap_CS_fsm_pp1_stage7) & (1'b0 == ap_block_pp1_stage7_11001)) | ((1'b1 == ap_CS_fsm_pp1_stage6) & (1'b0 == ap_block_pp1_stage6_11001)) | ((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)) | ((1'b1 == ap_CS_fsm_pp1_stage5) & (1'b0 == ap_block_pp1_stage5_11001)) | ((1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1_11001)))) begin
        grp_fu_379_ce = 1'b1;
    end else begin
        grp_fu_379_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage5) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage5))) begin
        grp_fu_379_p0 = dense_array_load_9_reg_731;
    end else if (((1'b1 == ap_CS_fsm_pp1_stage4) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage4))) begin
        grp_fu_379_p0 = dense_array_load_8_reg_726;
    end else if (((1'b1 == ap_CS_fsm_pp1_stage3) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage3))) begin
        grp_fu_379_p0 = dense_array_load_7_reg_721;
    end else if (((1'b1 == ap_CS_fsm_pp1_stage2) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage2))) begin
        grp_fu_379_p0 = dense_array_load_6_reg_716;
    end else if (((1'b1 == ap_CS_fsm_pp1_stage1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage1))) begin
        grp_fu_379_p0 = dense_array_load_5_reg_711;
    end else if (((1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage0))) begin
        grp_fu_379_p0 = dense_array_load_4_reg_706;
    end else if (((1'b1 == ap_CS_fsm_pp1_stage9) & (1'b0 == ap_block_pp1_stage9) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        grp_fu_379_p0 = dense_array_load_3_reg_701;
    end else if (((1'b1 == ap_CS_fsm_pp1_stage8) & (1'b0 == ap_block_pp1_stage8) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        grp_fu_379_p0 = dense_array_load_2_reg_696;
    end else if (((1'b1 == ap_CS_fsm_pp1_stage7) & (1'b0 == ap_block_pp1_stage7) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        grp_fu_379_p0 = dense_array_load_1_reg_691;
    end else if (((1'b1 == ap_CS_fsm_pp1_stage6) & (1'b0 == ap_block_pp1_stage6) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        grp_fu_379_p0 = dense_array_load_reg_686;
    end else begin
        grp_fu_379_p0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage0)) | ((1'b1 == ap_CS_fsm_pp1_stage5) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage5)))) begin
        grp_fu_379_p1 = reg_407;
    end else if ((((1'b1 == ap_CS_fsm_pp1_stage4) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage4)) | ((1'b1 == ap_CS_fsm_pp1_stage9) & (1'b0 == ap_block_pp1_stage9) & (ap_enable_reg_pp1_iter0 == 1'b1)))) begin
        grp_fu_379_p1 = reg_402;
    end else if ((((1'b1 == ap_CS_fsm_pp1_stage3) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage3)) | ((1'b1 == ap_CS_fsm_pp1_stage8) & (1'b0 == ap_block_pp1_stage8) & (ap_enable_reg_pp1_iter0 == 1'b1)))) begin
        grp_fu_379_p1 = reg_397;
    end else if ((((1'b1 == ap_CS_fsm_pp1_stage2) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage2)) | ((1'b1 == ap_CS_fsm_pp1_stage7) & (1'b0 == ap_block_pp1_stage7) & (ap_enable_reg_pp1_iter0 == 1'b1)))) begin
        grp_fu_379_p1 = reg_392;
    end else if ((((1'b1 == ap_CS_fsm_pp1_stage6) & (1'b0 == ap_block_pp1_stage6) & (ap_enable_reg_pp1_iter0 == 1'b1)) | ((1'b1 == ap_CS_fsm_pp1_stage1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage1)))) begin
        grp_fu_379_p1 = reg_387;
    end else begin
        grp_fu_379_p1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp1_stage4) & (1'b0 == ap_block_pp1_stage4_11001)) | ((1'b1 == ap_CS_fsm_pp1_stage9) & (1'b0 == ap_block_pp1_stage9_11001)) | ((1'b1 == ap_CS_fsm_pp1_stage3) & (1'b0 == ap_block_pp1_stage3_11001)) | ((1'b1 == ap_CS_fsm_pp1_stage8) & (1'b0 == ap_block_pp1_stage8_11001)) | ((1'b1 == ap_CS_fsm_pp1_stage2) & (1'b0 == ap_block_pp1_stage2_11001)) | ((1'b1 == ap_CS_fsm_pp1_stage7) & (1'b0 == ap_block_pp1_stage7_11001)) | ((1'b1 == ap_CS_fsm_pp1_stage6) & (1'b0 == ap_block_pp1_stage6_11001)) | ((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)) | ((1'b1 == ap_CS_fsm_pp1_stage5) & (1'b0 == ap_block_pp1_stage5_11001)) | ((1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1_11001)))) begin
        grp_fu_383_ce = 1'b1;
    end else begin
        grp_fu_383_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage1))) begin
        grp_fu_383_p0 = dense_weights_9_load_reg_681;
    end else if (((1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage0))) begin
        grp_fu_383_p0 = dense_weights_8_load_reg_676;
    end else if (((1'b1 == ap_CS_fsm_pp1_stage9) & (1'b0 == ap_block_pp1_stage9) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        grp_fu_383_p0 = dense_weights_7_load_reg_671;
    end else if (((1'b1 == ap_CS_fsm_pp1_stage8) & (1'b0 == ap_block_pp1_stage8) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        grp_fu_383_p0 = dense_weights_6_load_reg_666;
    end else if (((1'b1 == ap_CS_fsm_pp1_stage7) & (1'b0 == ap_block_pp1_stage7) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        grp_fu_383_p0 = dense_weights_5_load_reg_661;
    end else if (((1'b1 == ap_CS_fsm_pp1_stage6) & (1'b0 == ap_block_pp1_stage6) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        grp_fu_383_p0 = dense_weights_4_load_reg_656;
    end else if (((1'b1 == ap_CS_fsm_pp1_stage5) & (1'b0 == ap_block_pp1_stage5) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        grp_fu_383_p0 = dense_weights_3_load_reg_651;
    end else if (((1'b1 == ap_CS_fsm_pp1_stage4) & (1'b0 == ap_block_pp1_stage4) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        grp_fu_383_p0 = dense_weights_2_load_reg_646;
    end else if (((1'b1 == ap_CS_fsm_pp1_stage3) & (1'b0 == ap_block_pp1_stage3) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        grp_fu_383_p0 = dense_weights_1_load_reg_641;
    end else if (((1'b1 == ap_CS_fsm_pp1_stage2) & (1'b0 == ap_block_pp1_stage2) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        grp_fu_383_p0 = dense_weights_0_load_reg_636;
    end else begin
        grp_fu_383_p0 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((exitcond126_fu_428_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_pp1_stage0;
        end
        ap_ST_fsm_pp1_stage0 : begin
            if ((~((icmp_ln49_fu_450_p2 == 1'd1) & (ap_enable_reg_pp1_iter1 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter0 == 1'b1)) & ~((ap_enable_reg_pp1_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone)) & (1'b0 == ap_block_pp1_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage1;
            end else if ((((ap_enable_reg_pp1_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone)) | ((icmp_ln49_fu_450_p2 == 1'd1) & (ap_enable_reg_pp1_iter1 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_pp1_stage1 : begin
            if ((1'b0 == ap_block_pp1_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage1;
            end
        end
        ap_ST_fsm_pp1_stage2 : begin
            if ((1'b0 == ap_block_pp1_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage2;
            end
        end
        ap_ST_fsm_pp1_stage3 : begin
            if ((1'b0 == ap_block_pp1_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage3;
            end
        end
        ap_ST_fsm_pp1_stage4 : begin
            if ((1'b0 == ap_block_pp1_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage4;
            end
        end
        ap_ST_fsm_pp1_stage5 : begin
            if ((1'b0 == ap_block_pp1_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage5;
            end
        end
        ap_ST_fsm_pp1_stage6 : begin
            if ((1'b0 == ap_block_pp1_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage6;
            end
        end
        ap_ST_fsm_pp1_stage7 : begin
            if ((1'b0 == ap_block_pp1_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage7;
            end
        end
        ap_ST_fsm_pp1_stage8 : begin
            if ((1'b0 == ap_block_pp1_stage8_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage8;
            end
        end
        ap_ST_fsm_pp1_stage9 : begin
            if ((1'b0 == ap_block_pp1_stage9_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage9;
            end
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_pp2_stage0;
        end
        ap_ST_fsm_pp2_stage0 : begin
            if (~((icmp_ln60_fu_485_p2 == 1'd1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end else if (((icmp_ln60_fu_485_p2 == 1'd1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln49_fu_444_p2 = (ap_phi_mux_i_phi_fu_361_p4 + 8'd1);

assign add_ln60_fu_479_p2 = (j_reg_368 + 4'd1);

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp1_stage1 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp1_stage2 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp1_stage3 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp1_stage4 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_pp1_stage5 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_pp1_stage6 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_pp1_stage7 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_pp1_stage8 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_pp1_stage9 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_pp2_stage0 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp1_stage1_11001 = ((flat_to_dense_stream_V_empty_n == 1'b0) & (icmp_ln49_reg_577 == 1'd0) & (ap_enable_reg_pp1_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp1_stage1_subdone = ((flat_to_dense_stream_V_empty_n == 1'b0) & (icmp_ln49_reg_577 == 1'd0) & (ap_enable_reg_pp1_iter0 == 1'b1));
end

assign ap_block_pp1_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage5 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage5_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage5_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage6 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage6_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage6_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage7 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage7_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage7_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage8 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage8_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage8_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage9 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage9_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage9_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp2_stage0_01001 = ((dense_to_softmax_stream_V_full_n == 1'b0) & (icmp_ln60_reg_741 == 1'd0) & (ap_enable_reg_pp2_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp2_stage0_11001 = ((dense_to_softmax_stream_V_full_n == 1'b0) & (icmp_ln60_reg_741 == 1'd0) & (ap_enable_reg_pp2_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp2_stage0_subdone = ((dense_to_softmax_stream_V_full_n == 1'b0) & (icmp_ln60_reg_741 == 1'd0) & (ap_enable_reg_pp2_iter1 == 1'b1));
end

assign ap_block_state10_pp1_stage6_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp1_stage7_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp1_stage8_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp1_stage9_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp1_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp1_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp1_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp1_stage3_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp1_stage4_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp1_stage5_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp1_stage6_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp1_stage7_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp1_stage8_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp1_stage9_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp1_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp2_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state27_pp2_stage0_iter1 = ((dense_to_softmax_stream_V_full_n == 1'b0) & (icmp_ln60_reg_741 == 1'd0));
end

assign ap_block_state4_pp1_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state5_pp1_stage1_iter0 = ((flat_to_dense_stream_V_empty_n == 1'b0) & (icmp_ln49_reg_577 == 1'd0));
end

assign ap_block_state6_pp1_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp1_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp1_stage4_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp1_stage5_iter0 = ~(1'b1 == 1'b1);

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

assign ap_enable_pp2 = (ap_idle_pp2 ^ 1'b1);

assign dense_to_softmax_stream_V_din = dense_array_q1;

assign dense_weights_0_address0 = zext_ln56_fu_465_p1;

assign dense_weights_1_address0 = zext_ln56_fu_465_p1;

assign dense_weights_2_address0 = zext_ln56_fu_465_p1;

assign dense_weights_3_address0 = zext_ln56_fu_465_p1;

assign dense_weights_4_address0 = zext_ln56_fu_465_p1;

assign dense_weights_5_address0 = zext_ln56_fu_465_p1;

assign dense_weights_6_address0 = zext_ln56_fu_465_p1;

assign dense_weights_7_address0 = zext_ln56_fu_465_p1;

assign dense_weights_8_address0 = zext_ln56_fu_465_p1;

assign dense_weights_9_address0 = zext_ln56_fu_465_p1;

assign empty_21_fu_422_p2 = (empty_reg_346 + 4'd1);

assign empty_24_fu_460_p2 = (i_cast_fu_456_p1 + mul_reg_509);

assign exitcond126_fu_428_p2 = ((empty_reg_346 == 4'd10) ? 1'b1 : 1'b0);

assign filter_cast_fu_418_p1 = filter;

assign i_cast_fu_456_p1 = ap_phi_mux_i_phi_fu_361_p4;

assign icmp_ln49_fu_450_p2 = ((ap_phi_mux_i_phi_fu_361_p4 == 8'd196) ? 1'b1 : 1'b0);

assign icmp_ln60_fu_485_p2 = ((j_reg_368 == 4'd10) ? 1'b1 : 1'b0);

assign j_cast_fu_491_p1 = j_reg_368;

assign mul_fu_439_p0 = filter_cast_reg_496;

assign mul_fu_439_p1 = 10'd196;

assign p_cast_fu_434_p1 = empty_reg_346;

assign zext_ln56_fu_465_p1 = empty_24_fu_460_p2;

always @ (posedge ap_clk) begin
    filter_cast_reg_496[9:2] <= 8'b00000000;
end

endmodule //cnn_stream_accel_dense
