// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="cnn_stream_accel_cnn_stream_accel,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.280380,HLS_SYN_LAT=47267,HLS_SYN_TPT=none,HLS_SYN_MEM=122,HLS_SYN_DSP=0,HLS_SYN_FF=34853,HLS_SYN_LUT=31974,HLS_VERSION=2020_2}" *)

module cnn_stream_accel (
        ap_clk,
        ap_rst_n,
        in_stream_TDATA,
        in_stream_TVALID,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TUSER,
        in_stream_TLAST,
        in_stream_TID,
        in_stream_TDEST,
        out_stream_TDATA,
        out_stream_TVALID,
        out_stream_TREADY,
        out_stream_TKEEP,
        out_stream_TSTRB,
        out_stream_TUSER,
        out_stream_TLAST,
        out_stream_TID,
        out_stream_TDEST,
        s_axi_CTRL_AWVALID,
        s_axi_CTRL_AWREADY,
        s_axi_CTRL_AWADDR,
        s_axi_CTRL_WVALID,
        s_axi_CTRL_WREADY,
        s_axi_CTRL_WDATA,
        s_axi_CTRL_WSTRB,
        s_axi_CTRL_ARVALID,
        s_axi_CTRL_ARREADY,
        s_axi_CTRL_ARADDR,
        s_axi_CTRL_RVALID,
        s_axi_CTRL_RREADY,
        s_axi_CTRL_RDATA,
        s_axi_CTRL_RRESP,
        s_axi_CTRL_BVALID,
        s_axi_CTRL_BREADY,
        s_axi_CTRL_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 12'd1;
parameter    ap_ST_fsm_pp0_stage0 = 12'd2;
parameter    ap_ST_fsm_state4 = 12'd4;
parameter    ap_ST_fsm_state5 = 12'd8;
parameter    ap_ST_fsm_state6 = 12'd16;
parameter    ap_ST_fsm_pp2_stage0 = 12'd32;
parameter    ap_ST_fsm_state27 = 12'd64;
parameter    ap_ST_fsm_pp3_stage0 = 12'd128;
parameter    ap_ST_fsm_state31 = 12'd256;
parameter    ap_ST_fsm_state32 = 12'd512;
parameter    ap_ST_fsm_pp4_stage0 = 12'd1024;
parameter    ap_ST_fsm_state36 = 12'd2048;
parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 4;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [31:0] in_stream_TDATA;
input   in_stream_TVALID;
output   in_stream_TREADY;
input  [3:0] in_stream_TKEEP;
input  [3:0] in_stream_TSTRB;
input  [0:0] in_stream_TUSER;
input  [0:0] in_stream_TLAST;
input  [0:0] in_stream_TID;
input  [0:0] in_stream_TDEST;
output  [31:0] out_stream_TDATA;
output   out_stream_TVALID;
input   out_stream_TREADY;
output  [3:0] out_stream_TKEEP;
output  [3:0] out_stream_TSTRB;
output  [0:0] out_stream_TUSER;
output  [0:0] out_stream_TLAST;
output  [0:0] out_stream_TID;
output  [0:0] out_stream_TDEST;
input   s_axi_CTRL_AWVALID;
output   s_axi_CTRL_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_AWADDR;
input   s_axi_CTRL_WVALID;
output   s_axi_CTRL_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_CTRL_WSTRB;
input   s_axi_CTRL_ARVALID;
output   s_axi_CTRL_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_ARADDR;
output   s_axi_CTRL_RVALID;
input   s_axi_CTRL_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_RDATA;
output  [1:0] s_axi_CTRL_RRESP;
output   s_axi_CTRL_BVALID;
input   s_axi_CTRL_BREADY;
output  [1:0] s_axi_CTRL_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [11:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
reg    in_stream_TDATA_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
wire   [0:0] icmp_ln27_fu_500_p2;
reg    out_stream_TDATA_blk_n;
wire    ap_CS_fsm_pp4_stage0;
reg    ap_enable_reg_pp4_iter1;
wire    ap_block_pp4_stage0;
reg   [0:0] icmp_ln40_reg_995;
reg    ap_enable_reg_pp4_iter2;
reg   [0:0] icmp_ln40_reg_995_pp4_iter1_reg;
reg   [9:0] indvar_flatten_reg_337;
reg   [4:0] i_reg_348;
reg   [4:0] j_reg_359;
reg   [9:0] indvar_flatten7_reg_381;
reg   [4:0] r_reg_392;
reg   [4:0] c_reg_403;
reg   [10:0] indvar_flatten15_reg_414;
reg   [5:0] i_1_reg_425;
reg   [5:0] j_1_reg_436;
reg   [3:0] i_2_reg_447;
wire   [9:0] add_ln27_1_fu_494_p2;
reg    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln27_reg_865;
wire   [4:0] select_ln27_fu_518_p3;
reg   [4:0] select_ln27_reg_869;
wire   [4:0] select_ln27_1_fu_526_p3;
reg   [4:0] select_ln27_1_reg_874;
reg   [31:0] temp_in_data_V_reg_881;
wire   [4:0] add_ln28_fu_538_p2;
wire   [10:0] empty_49_fu_586_p2;
wire    ap_CS_fsm_state5;
wire   [9:0] add_ln16_2_fu_603_p2;
wire    ap_CS_fsm_pp2_stage0;
reg    ap_enable_reg_pp2_iter0;
wire    ap_block_state7_pp2_stage0_iter0;
wire    ap_block_state8_pp2_stage0_iter1;
wire    ap_block_state9_pp2_stage0_iter2;
wire    ap_block_state10_pp2_stage0_iter3;
wire    ap_block_state11_pp2_stage0_iter4;
wire    ap_block_state12_pp2_stage0_iter5;
wire    ap_block_state13_pp2_stage0_iter6;
wire    ap_block_state14_pp2_stage0_iter7;
wire    ap_block_state15_pp2_stage0_iter8;
wire    ap_block_state16_pp2_stage0_iter9;
wire    ap_block_state17_pp2_stage0_iter10;
wire    ap_block_state18_pp2_stage0_iter11;
wire    ap_block_state19_pp2_stage0_iter12;
wire    ap_block_state20_pp2_stage0_iter13;
wire    ap_block_state21_pp2_stage0_iter14;
wire    ap_block_state22_pp2_stage0_iter15;
wire    ap_block_state23_pp2_stage0_iter16;
wire    ap_block_state24_pp2_stage0_iter17;
wire    ap_block_state25_pp2_stage0_iter18;
wire    ap_block_state26_pp2_stage0_iter19;
wire    ap_block_pp2_stage0_11001;
wire   [0:0] icmp_ln16_fu_609_p2;
reg   [0:0] icmp_ln16_reg_904;
reg   [0:0] icmp_ln16_reg_904_pp2_iter1_reg;
reg   [0:0] icmp_ln16_reg_904_pp2_iter2_reg;
reg   [0:0] icmp_ln16_reg_904_pp2_iter3_reg;
reg   [0:0] icmp_ln16_reg_904_pp2_iter4_reg;
reg   [0:0] icmp_ln16_reg_904_pp2_iter5_reg;
reg   [0:0] icmp_ln16_reg_904_pp2_iter6_reg;
reg   [0:0] icmp_ln16_reg_904_pp2_iter7_reg;
reg   [0:0] icmp_ln16_reg_904_pp2_iter8_reg;
reg   [0:0] icmp_ln16_reg_904_pp2_iter9_reg;
reg   [0:0] icmp_ln16_reg_904_pp2_iter10_reg;
reg   [0:0] icmp_ln16_reg_904_pp2_iter11_reg;
reg   [0:0] icmp_ln16_reg_904_pp2_iter12_reg;
reg   [0:0] icmp_ln16_reg_904_pp2_iter13_reg;
reg   [0:0] icmp_ln16_reg_904_pp2_iter14_reg;
reg   [0:0] icmp_ln16_reg_904_pp2_iter15_reg;
reg   [0:0] icmp_ln16_reg_904_pp2_iter16_reg;
reg   [0:0] icmp_ln16_reg_904_pp2_iter17_reg;
reg   [0:0] icmp_ln16_reg_904_pp2_iter18_reg;
wire   [4:0] select_ln16_fu_627_p3;
reg   [4:0] select_ln16_reg_908;
wire   [4:0] select_ln16_1_fu_635_p3;
reg   [4:0] select_ln16_1_reg_914;
wire   [4:0] add_ln16_1_fu_651_p2;
reg   [4:0] add_ln16_1_reg_921;
wire   [4:0] add_ln18_fu_657_p2;
wire   [10:0] add_ln22_3_fu_738_p2;
reg   [10:0] add_ln22_3_reg_937;
reg   [10:0] add_ln22_3_reg_937_pp2_iter2_reg;
reg   [10:0] add_ln22_3_reg_937_pp2_iter3_reg;
reg   [10:0] add_ln22_3_reg_937_pp2_iter4_reg;
reg   [10:0] add_ln22_3_reg_937_pp2_iter5_reg;
reg   [10:0] add_ln22_3_reg_937_pp2_iter6_reg;
reg   [10:0] add_ln22_3_reg_937_pp2_iter7_reg;
reg   [10:0] add_ln22_3_reg_937_pp2_iter8_reg;
reg   [10:0] add_ln22_3_reg_937_pp2_iter9_reg;
reg   [10:0] add_ln22_3_reg_937_pp2_iter10_reg;
reg   [10:0] add_ln22_3_reg_937_pp2_iter11_reg;
reg   [10:0] add_ln22_3_reg_937_pp2_iter12_reg;
reg   [10:0] add_ln22_3_reg_937_pp2_iter13_reg;
reg   [10:0] add_ln22_3_reg_937_pp2_iter14_reg;
reg   [10:0] add_ln22_3_reg_937_pp2_iter15_reg;
reg   [10:0] add_ln22_3_reg_937_pp2_iter16_reg;
reg   [10:0] add_ln22_3_reg_937_pp2_iter17_reg;
reg   [10:0] add_ln22_3_reg_937_pp2_iter18_reg;
wire   [31:0] img_buffer_q0;
reg   [31:0] img_buffer_load_reg_942;
reg    ap_enable_reg_pp2_iter2;
wire   [31:0] grp_fu_489_p2;
reg   [31:0] conv4_i_i_reg_947;
reg    ap_enable_reg_pp2_iter18;
wire   [10:0] add_ln96_1_fu_748_p2;
wire    ap_CS_fsm_pp3_stage0;
reg    ap_enable_reg_pp3_iter0;
wire    ap_block_state28_pp3_stage0_iter0;
wire    ap_block_state29_pp3_stage0_iter1;
wire    ap_block_state30_pp3_stage0_iter2;
wire    ap_block_pp3_stage0_11001;
wire   [0:0] icmp_ln96_fu_754_p2;
reg   [0:0] icmp_ln96_reg_957;
reg   [0:0] icmp_ln96_reg_957_pp3_iter1_reg;
wire   [5:0] select_ln96_fu_772_p3;
reg   [5:0] select_ln96_reg_961;
wire   [5:0] select_ln96_1_fu_780_p3;
reg   [5:0] select_ln96_1_reg_966;
wire   [5:0] add_ln98_fu_788_p2;
wire   [63:0] zext_ln100_2_fu_827_p1;
reg   [63:0] zext_ln100_2_reg_978;
wire   [3:0] add_ln40_fu_832_p2;
reg    ap_enable_reg_pp4_iter0;
wire    ap_block_state33_pp4_stage0_iter0;
reg    ap_block_state34_pp4_stage0_iter1;
reg    ap_block_state34_io;
reg    ap_block_state35_pp4_stage0_iter2;
reg    ap_block_state35_io;
reg    ap_block_pp4_stage0_11001;
wire   [0:0] icmp_ln40_fu_838_p2;
wire   [0:0] temp_out_last_V_fu_849_p2;
reg   [0:0] temp_out_last_V_reg_1004;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_enable_reg_pp0_iter1;
wire    ap_CS_fsm_state6;
wire    ap_block_pp2_stage0_subdone;
reg    ap_condition_pp2_exit_iter0_state7;
reg    ap_enable_reg_pp2_iter1;
reg    ap_enable_reg_pp2_iter3;
reg    ap_enable_reg_pp2_iter4;
reg    ap_enable_reg_pp2_iter5;
reg    ap_enable_reg_pp2_iter6;
reg    ap_enable_reg_pp2_iter7;
reg    ap_enable_reg_pp2_iter8;
reg    ap_enable_reg_pp2_iter9;
reg    ap_enable_reg_pp2_iter10;
reg    ap_enable_reg_pp2_iter11;
reg    ap_enable_reg_pp2_iter12;
reg    ap_enable_reg_pp2_iter13;
reg    ap_enable_reg_pp2_iter14;
reg    ap_enable_reg_pp2_iter15;
reg    ap_enable_reg_pp2_iter16;
reg    ap_enable_reg_pp2_iter17;
reg    ap_enable_reg_pp2_iter19;
wire    ap_CS_fsm_state27;
wire    ap_block_pp3_stage0_subdone;
reg    ap_condition_pp3_exit_iter0_state28;
reg    ap_enable_reg_pp3_iter1;
reg    ap_enable_reg_pp3_iter2;
wire    ap_CS_fsm_state32;
wire    grp_dataflow_section_fu_458_ap_ready;
wire    grp_dataflow_section_fu_458_ap_done;
reg    ap_block_pp4_stage0_subdone;
reg    ap_condition_pp4_exit_iter0_state33;
reg   [10:0] pad_img0_address0;
reg    pad_img0_ce0;
reg    pad_img0_we0;
reg   [31:0] pad_img0_d0;
wire   [31:0] pad_img0_q0;
reg    pad_img0_ce1;
wire   [31:0] pad_img0_q1;
reg   [10:0] pad_img1_address0;
reg    pad_img1_ce0;
reg    pad_img1_we0;
wire   [31:0] pad_img1_q0;
reg    pad_img1_ce1;
wire   [31:0] pad_img1_q1;
reg   [10:0] pad_img2_address0;
reg    pad_img2_ce0;
reg    pad_img2_we0;
wire   [31:0] pad_img2_q0;
reg    pad_img2_ce1;
wire   [31:0] pad_img2_q1;
reg   [10:0] pad_img3_address0;
reg    pad_img3_ce0;
reg    pad_img3_we0;
wire   [31:0] pad_img3_q0;
reg    pad_img3_ce1;
wire   [31:0] pad_img3_q1;
reg   [9:0] img_buffer_address0;
reg    img_buffer_ce0;
reg    img_buffer_we0;
wire   [31:0] img_buffer_d0;
reg   [3:0] output_buffer_address0;
reg    output_buffer_ce0;
reg    output_buffer_we0;
wire   [31:0] output_buffer_q0;
reg    output_buffer_ce1;
wire   [31:0] output_buffer_q1;
wire    grp_dataflow_section_fu_458_ap_start;
wire    grp_dataflow_section_fu_458_ap_idle;
wire   [10:0] grp_dataflow_section_fu_458_pad_img0_address0;
wire    grp_dataflow_section_fu_458_pad_img0_ce0;
wire   [10:0] grp_dataflow_section_fu_458_pad_img0_address1;
wire    grp_dataflow_section_fu_458_pad_img0_ce1;
wire   [10:0] grp_dataflow_section_fu_458_pad_img1_address0;
wire    grp_dataflow_section_fu_458_pad_img1_ce0;
wire   [10:0] grp_dataflow_section_fu_458_pad_img1_address1;
wire    grp_dataflow_section_fu_458_pad_img1_ce1;
wire   [10:0] grp_dataflow_section_fu_458_pad_img2_address0;
wire    grp_dataflow_section_fu_458_pad_img2_ce0;
wire   [10:0] grp_dataflow_section_fu_458_pad_img2_address1;
wire    grp_dataflow_section_fu_458_pad_img2_ce1;
wire   [10:0] grp_dataflow_section_fu_458_pad_img3_address0;
wire    grp_dataflow_section_fu_458_pad_img3_ce0;
wire   [10:0] grp_dataflow_section_fu_458_pad_img3_address1;
wire    grp_dataflow_section_fu_458_pad_img3_ce1;
wire   [3:0] grp_dataflow_section_fu_458_prediction_address0;
wire    grp_dataflow_section_fu_458_prediction_ce0;
wire    grp_dataflow_section_fu_458_prediction_we0;
wire   [31:0] grp_dataflow_section_fu_458_prediction_d0;
wire   [3:0] grp_dataflow_section_fu_458_prediction_address1;
wire    grp_dataflow_section_fu_458_prediction_ce1;
wire   [31:0] grp_dataflow_section_fu_458_grp_fu_489_p_din0;
wire   [31:0] grp_dataflow_section_fu_458_grp_fu_489_p_din1;
wire   [31:0] grp_dataflow_section_fu_458_grp_fu_489_p_dout0;
wire    grp_dataflow_section_fu_458_grp_fu_489_p_ce;
reg   [4:0] ap_phi_mux_i_phi_fu_352_p4;
reg   [10:0] empty_48_reg_370;
wire   [0:0] exitcond15210_fu_592_p2;
wire    ap_CS_fsm_state4;
reg   [4:0] ap_phi_mux_r_phi_fu_396_p4;
wire    ap_block_pp2_stage0;
reg   [5:0] ap_phi_mux_i_1_phi_fu_429_p4;
wire    ap_block_pp3_stage0;
reg    grp_dataflow_section_fu_458_ap_start_reg;
wire    ap_CS_fsm_state31;
wire   [63:0] zext_ln32_2_fu_577_p1;
wire   [63:0] p_cast_fu_598_p1;
wire   [63:0] zext_ln22_4_fu_724_p1;
wire   [63:0] zext_ln22_6_fu_744_p1;
wire   [63:0] zext_ln40_fu_844_p1;
reg    ap_block_pp4_stage0_01001;
reg   [31:0] grp_fu_489_p0;
reg   [31:0] grp_fu_489_p1;
wire   [0:0] icmp_ln2826_fu_512_p2;
wire   [4:0] add_ln27_fu_506_p2;
wire   [6:0] tmp_s_fu_551_p3;
wire   [9:0] tmp_fu_544_p3;
wire   [9:0] zext_ln32_fu_558_p1;
wire   [9:0] sub_ln32_fu_562_p2;
wire   [9:0] zext_ln32_1_fu_568_p1;
wire   [9:0] add_ln32_fu_571_p2;
wire   [0:0] icmp_ln18_fu_621_p2;
wire   [4:0] add_ln16_fu_615_p2;
wire   [4:0] select_ln16_2_fu_643_p3;
wire   [6:0] tmp_66_fu_670_p3;
wire   [9:0] tmp_65_fu_663_p3;
wire   [9:0] zext_ln22_fu_677_p1;
wire   [9:0] tmp_67_fu_687_p3;
wire   [5:0] tmp_68_fu_698_p3;
wire   [10:0] zext_ln22_1_fu_694_p1;
wire   [10:0] zext_ln22_2_fu_705_p1;
wire   [9:0] sub_ln22_fu_681_p2;
wire   [9:0] zext_ln22_3_fu_715_p1;
wire   [9:0] add_ln22_2_fu_718_p2;
wire   [4:0] add_ln22_fu_729_p2;
wire   [10:0] add_ln22_1_fu_709_p2;
wire   [10:0] zext_ln22_5_fu_734_p1;
wire   [0:0] icmp_ln98_fu_766_p2;
wire   [5:0] add_ln96_fu_760_p2;
wire   [6:0] tmp_70_fu_801_p3;
wire   [10:0] tmp_69_fu_794_p3;
wire   [10:0] zext_ln100_fu_808_p1;
wire   [10:0] add_ln100_fu_812_p2;
wire   [10:0] zext_ln100_1_fu_818_p1;
wire   [10:0] add_ln100_1_fu_821_p2;
reg    grp_fu_489_ce;
wire    ap_CS_fsm_state36;
wire    regslice_both_out_stream_V_data_V_U_apdone_blk;
reg   [11:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_idle_pp2;
wire    ap_enable_pp2;
reg    ap_idle_pp3;
wire    ap_enable_pp3;
reg    ap_idle_pp4;
wire    ap_enable_pp4;
wire    regslice_both_in_stream_V_data_V_U_apdone_blk;
wire   [31:0] in_stream_TDATA_int_regslice;
wire    in_stream_TVALID_int_regslice;
reg    in_stream_TREADY_int_regslice;
wire    regslice_both_in_stream_V_data_V_U_ack_in;
wire    regslice_both_in_stream_V_keep_V_U_apdone_blk;
wire   [3:0] in_stream_TKEEP_int_regslice;
wire    regslice_both_in_stream_V_keep_V_U_vld_out;
wire    regslice_both_in_stream_V_keep_V_U_ack_in;
wire    regslice_both_in_stream_V_strb_V_U_apdone_blk;
wire   [3:0] in_stream_TSTRB_int_regslice;
wire    regslice_both_in_stream_V_strb_V_U_vld_out;
wire    regslice_both_in_stream_V_strb_V_U_ack_in;
wire    regslice_both_in_stream_V_user_V_U_apdone_blk;
wire   [0:0] in_stream_TUSER_int_regslice;
wire    regslice_both_in_stream_V_user_V_U_vld_out;
wire    regslice_both_in_stream_V_user_V_U_ack_in;
wire    regslice_both_in_stream_V_last_V_U_apdone_blk;
wire   [0:0] in_stream_TLAST_int_regslice;
wire    regslice_both_in_stream_V_last_V_U_vld_out;
wire    regslice_both_in_stream_V_last_V_U_ack_in;
wire    regslice_both_in_stream_V_id_V_U_apdone_blk;
wire   [0:0] in_stream_TID_int_regslice;
wire    regslice_both_in_stream_V_id_V_U_vld_out;
wire    regslice_both_in_stream_V_id_V_U_ack_in;
wire    regslice_both_in_stream_V_dest_V_U_apdone_blk;
wire   [0:0] in_stream_TDEST_int_regslice;
wire    regslice_both_in_stream_V_dest_V_U_vld_out;
wire    regslice_both_in_stream_V_dest_V_U_ack_in;
wire   [31:0] out_stream_TDATA_int_regslice;
reg    out_stream_TVALID_int_regslice;
wire    out_stream_TREADY_int_regslice;
wire    regslice_both_out_stream_V_data_V_U_vld_out;
wire    regslice_both_out_stream_V_keep_V_U_apdone_blk;
wire    regslice_both_out_stream_V_keep_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_keep_V_U_vld_out;
wire    regslice_both_out_stream_V_strb_V_U_apdone_blk;
wire    regslice_both_out_stream_V_strb_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_strb_V_U_vld_out;
wire    regslice_both_out_stream_V_user_V_U_apdone_blk;
wire    regslice_both_out_stream_V_user_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_user_V_U_vld_out;
wire    regslice_both_out_stream_V_last_V_U_apdone_blk;
wire    regslice_both_out_stream_V_last_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_last_V_U_vld_out;
wire    regslice_both_out_stream_V_id_V_U_apdone_blk;
wire    regslice_both_out_stream_V_id_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_id_V_U_vld_out;
wire    regslice_both_out_stream_V_dest_V_U_apdone_blk;
wire    regslice_both_out_stream_V_dest_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_dest_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 12'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp4_iter1 = 1'b0;
#0 ap_enable_reg_pp4_iter2 = 1'b0;
#0 ap_enable_reg_pp2_iter0 = 1'b0;
#0 ap_enable_reg_pp2_iter2 = 1'b0;
#0 ap_enable_reg_pp2_iter18 = 1'b0;
#0 ap_enable_reg_pp3_iter0 = 1'b0;
#0 ap_enable_reg_pp4_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp2_iter1 = 1'b0;
#0 ap_enable_reg_pp2_iter3 = 1'b0;
#0 ap_enable_reg_pp2_iter4 = 1'b0;
#0 ap_enable_reg_pp2_iter5 = 1'b0;
#0 ap_enable_reg_pp2_iter6 = 1'b0;
#0 ap_enable_reg_pp2_iter7 = 1'b0;
#0 ap_enable_reg_pp2_iter8 = 1'b0;
#0 ap_enable_reg_pp2_iter9 = 1'b0;
#0 ap_enable_reg_pp2_iter10 = 1'b0;
#0 ap_enable_reg_pp2_iter11 = 1'b0;
#0 ap_enable_reg_pp2_iter12 = 1'b0;
#0 ap_enable_reg_pp2_iter13 = 1'b0;
#0 ap_enable_reg_pp2_iter14 = 1'b0;
#0 ap_enable_reg_pp2_iter15 = 1'b0;
#0 ap_enable_reg_pp2_iter16 = 1'b0;
#0 ap_enable_reg_pp2_iter17 = 1'b0;
#0 ap_enable_reg_pp2_iter19 = 1'b0;
#0 ap_enable_reg_pp3_iter1 = 1'b0;
#0 ap_enable_reg_pp3_iter2 = 1'b0;
#0 grp_dataflow_section_fu_458_ap_start_reg = 1'b0;
end

cnn_stream_accel_CTRL_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
CTRL_s_axi_U(
    .AWVALID(s_axi_CTRL_AWVALID),
    .AWREADY(s_axi_CTRL_AWREADY),
    .AWADDR(s_axi_CTRL_AWADDR),
    .WVALID(s_axi_CTRL_WVALID),
    .WREADY(s_axi_CTRL_WREADY),
    .WDATA(s_axi_CTRL_WDATA),
    .WSTRB(s_axi_CTRL_WSTRB),
    .ARVALID(s_axi_CTRL_ARVALID),
    .ARREADY(s_axi_CTRL_ARREADY),
    .ARADDR(s_axi_CTRL_ARADDR),
    .RVALID(s_axi_CTRL_RVALID),
    .RREADY(s_axi_CTRL_RREADY),
    .RDATA(s_axi_CTRL_RDATA),
    .RRESP(s_axi_CTRL_RRESP),
    .BVALID(s_axi_CTRL_BVALID),
    .BREADY(s_axi_CTRL_BREADY),
    .BRESP(s_axi_CTRL_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

cnn_stream_accel_pad_img0 #(
    .DataWidth( 32 ),
    .AddressRange( 1156 ),
    .AddressWidth( 11 ))
pad_img0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(pad_img0_address0),
    .ce0(pad_img0_ce0),
    .we0(pad_img0_we0),
    .d0(pad_img0_d0),
    .q0(pad_img0_q0),
    .address1(grp_dataflow_section_fu_458_pad_img0_address1),
    .ce1(pad_img0_ce1),
    .q1(pad_img0_q1)
);

cnn_stream_accel_pad_img0 #(
    .DataWidth( 32 ),
    .AddressRange( 1156 ),
    .AddressWidth( 11 ))
pad_img1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(pad_img1_address0),
    .ce0(pad_img1_ce0),
    .we0(pad_img1_we0),
    .d0(pad_img0_q0),
    .q0(pad_img1_q0),
    .address1(grp_dataflow_section_fu_458_pad_img1_address1),
    .ce1(pad_img1_ce1),
    .q1(pad_img1_q1)
);

cnn_stream_accel_pad_img0 #(
    .DataWidth( 32 ),
    .AddressRange( 1156 ),
    .AddressWidth( 11 ))
pad_img2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(pad_img2_address0),
    .ce0(pad_img2_ce0),
    .we0(pad_img2_we0),
    .d0(pad_img0_q0),
    .q0(pad_img2_q0),
    .address1(grp_dataflow_section_fu_458_pad_img2_address1),
    .ce1(pad_img2_ce1),
    .q1(pad_img2_q1)
);

cnn_stream_accel_pad_img0 #(
    .DataWidth( 32 ),
    .AddressRange( 1156 ),
    .AddressWidth( 11 ))
pad_img3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(pad_img3_address0),
    .ce0(pad_img3_ce0),
    .we0(pad_img3_we0),
    .d0(pad_img0_q0),
    .q0(pad_img3_q0),
    .address1(grp_dataflow_section_fu_458_pad_img3_address1),
    .ce1(pad_img3_ce1),
    .q1(pad_img3_q1)
);

cnn_stream_accel_img_buffer #(
    .DataWidth( 32 ),
    .AddressRange( 784 ),
    .AddressWidth( 10 ))
img_buffer_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(img_buffer_address0),
    .ce0(img_buffer_ce0),
    .we0(img_buffer_we0),
    .d0(img_buffer_d0),
    .q0(img_buffer_q0)
);

cnn_stream_accel_output_buffer #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
output_buffer_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(output_buffer_address0),
    .ce0(output_buffer_ce0),
    .we0(output_buffer_we0),
    .d0(grp_dataflow_section_fu_458_prediction_d0),
    .q0(output_buffer_q0),
    .address1(grp_dataflow_section_fu_458_prediction_address1),
    .ce1(output_buffer_ce1),
    .q1(output_buffer_q1)
);

cnn_stream_accel_dataflow_section grp_dataflow_section_fu_458(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_dataflow_section_fu_458_ap_start),
    .ap_done(grp_dataflow_section_fu_458_ap_done),
    .ap_idle(grp_dataflow_section_fu_458_ap_idle),
    .ap_ready(grp_dataflow_section_fu_458_ap_ready),
    .pad_img0_address0(grp_dataflow_section_fu_458_pad_img0_address0),
    .pad_img0_ce0(grp_dataflow_section_fu_458_pad_img0_ce0),
    .pad_img0_q0(pad_img0_q0),
    .pad_img0_address1(grp_dataflow_section_fu_458_pad_img0_address1),
    .pad_img0_ce1(grp_dataflow_section_fu_458_pad_img0_ce1),
    .pad_img0_q1(pad_img0_q1),
    .pad_img1_address0(grp_dataflow_section_fu_458_pad_img1_address0),
    .pad_img1_ce0(grp_dataflow_section_fu_458_pad_img1_ce0),
    .pad_img1_q0(pad_img1_q0),
    .pad_img1_address1(grp_dataflow_section_fu_458_pad_img1_address1),
    .pad_img1_ce1(grp_dataflow_section_fu_458_pad_img1_ce1),
    .pad_img1_q1(pad_img1_q1),
    .pad_img2_address0(grp_dataflow_section_fu_458_pad_img2_address0),
    .pad_img2_ce0(grp_dataflow_section_fu_458_pad_img2_ce0),
    .pad_img2_q0(pad_img2_q0),
    .pad_img2_address1(grp_dataflow_section_fu_458_pad_img2_address1),
    .pad_img2_ce1(grp_dataflow_section_fu_458_pad_img2_ce1),
    .pad_img2_q1(pad_img2_q1),
    .pad_img3_address0(grp_dataflow_section_fu_458_pad_img3_address0),
    .pad_img3_ce0(grp_dataflow_section_fu_458_pad_img3_ce0),
    .pad_img3_q0(pad_img3_q0),
    .pad_img3_address1(grp_dataflow_section_fu_458_pad_img3_address1),
    .pad_img3_ce1(grp_dataflow_section_fu_458_pad_img3_ce1),
    .pad_img3_q1(pad_img3_q1),
    .prediction_address0(grp_dataflow_section_fu_458_prediction_address0),
    .prediction_ce0(grp_dataflow_section_fu_458_prediction_ce0),
    .prediction_we0(grp_dataflow_section_fu_458_prediction_we0),
    .prediction_d0(grp_dataflow_section_fu_458_prediction_d0),
    .prediction_address1(grp_dataflow_section_fu_458_prediction_address1),
    .prediction_ce1(grp_dataflow_section_fu_458_prediction_ce1),
    .prediction_q1(output_buffer_q1),
    .grp_fu_489_p_din0(grp_dataflow_section_fu_458_grp_fu_489_p_din0),
    .grp_fu_489_p_din1(grp_dataflow_section_fu_458_grp_fu_489_p_din1),
    .grp_fu_489_p_dout0(grp_dataflow_section_fu_458_grp_fu_489_p_dout0),
    .grp_fu_489_p_ce(grp_dataflow_section_fu_458_grp_fu_489_p_ce)
);

cnn_stream_accel_fdiv_32ns_32ns_32_16_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 16 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fdiv_32ns_32ns_32_16_no_dsp_1_U116(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_489_p0),
    .din1(grp_fu_489_p1),
    .ce(grp_fu_489_ce),
    .dout(grp_fu_489_p2)
);

cnn_stream_accel_regslice_both #(
    .DataWidth( 32 ))
regslice_both_in_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TDATA),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_data_V_U_ack_in),
    .data_out(in_stream_TDATA_int_regslice),
    .vld_out(in_stream_TVALID_int_regslice),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_data_V_U_apdone_blk)
);

cnn_stream_accel_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TKEEP),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_keep_V_U_ack_in),
    .data_out(in_stream_TKEEP_int_regslice),
    .vld_out(regslice_both_in_stream_V_keep_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_keep_V_U_apdone_blk)
);

cnn_stream_accel_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TSTRB),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_strb_V_U_ack_in),
    .data_out(in_stream_TSTRB_int_regslice),
    .vld_out(regslice_both_in_stream_V_strb_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_strb_V_U_apdone_blk)
);

cnn_stream_accel_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TUSER),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_user_V_U_ack_in),
    .data_out(in_stream_TUSER_int_regslice),
    .vld_out(regslice_both_in_stream_V_user_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_user_V_U_apdone_blk)
);

cnn_stream_accel_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TLAST),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_last_V_U_ack_in),
    .data_out(in_stream_TLAST_int_regslice),
    .vld_out(regslice_both_in_stream_V_last_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_last_V_U_apdone_blk)
);

cnn_stream_accel_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TID),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_id_V_U_ack_in),
    .data_out(in_stream_TID_int_regslice),
    .vld_out(regslice_both_in_stream_V_id_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_id_V_U_apdone_blk)
);

cnn_stream_accel_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TDEST),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_dest_V_U_ack_in),
    .data_out(in_stream_TDEST_int_regslice),
    .vld_out(regslice_both_in_stream_V_dest_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_dest_V_U_apdone_blk)
);

cnn_stream_accel_regslice_both #(
    .DataWidth( 32 ))
regslice_both_out_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_stream_TDATA_int_regslice),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(out_stream_TREADY_int_regslice),
    .data_out(out_stream_TDATA),
    .vld_out(regslice_both_out_stream_V_data_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_data_V_U_apdone_blk)
);

cnn_stream_accel_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd15),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_keep_V_U_ack_in_dummy),
    .data_out(out_stream_TKEEP),
    .vld_out(regslice_both_out_stream_V_keep_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_keep_V_U_apdone_blk)
);

cnn_stream_accel_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd15),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_strb_V_U_ack_in_dummy),
    .data_out(out_stream_TSTRB),
    .vld_out(regslice_both_out_stream_V_strb_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_strb_V_U_apdone_blk)
);

cnn_stream_accel_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(1'd0),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_user_V_U_ack_in_dummy),
    .data_out(out_stream_TUSER),
    .vld_out(regslice_both_out_stream_V_user_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_user_V_U_apdone_blk)
);

cnn_stream_accel_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(temp_out_last_V_reg_1004),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_last_V_U_ack_in_dummy),
    .data_out(out_stream_TLAST),
    .vld_out(regslice_both_out_stream_V_last_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_last_V_U_apdone_blk)
);

cnn_stream_accel_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(1'd0),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_id_V_U_ack_in_dummy),
    .data_out(out_stream_TID),
    .vld_out(regslice_both_out_stream_V_id_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_id_V_U_apdone_blk)
);

cnn_stream_accel_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(1'd0),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_dest_V_U_ack_in_dummy),
    .data_out(out_stream_TDEST),
    .vld_out(regslice_both_out_stream_V_dest_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp2_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp2_stage0_subdone) & (1'b1 == ap_condition_pp2_exit_iter0_state7) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
            ap_enable_reg_pp2_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state6)) begin
            ap_enable_reg_pp2_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp2_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp2_exit_iter0_state7)) begin
                ap_enable_reg_pp2_iter1 <= (1'b1 ^ ap_condition_pp2_exit_iter0_state7);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp2_iter1 <= ap_enable_reg_pp2_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp2_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter10 <= ap_enable_reg_pp2_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp2_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter11 <= ap_enable_reg_pp2_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp2_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter12 <= ap_enable_reg_pp2_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp2_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter13 <= ap_enable_reg_pp2_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp2_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter14 <= ap_enable_reg_pp2_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp2_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter15 <= ap_enable_reg_pp2_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp2_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter16 <= ap_enable_reg_pp2_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp2_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter17 <= ap_enable_reg_pp2_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp2_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter18 <= ap_enable_reg_pp2_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp2_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter19 <= ap_enable_reg_pp2_iter18;
        end else if ((1'b1 == ap_CS_fsm_state6)) begin
            ap_enable_reg_pp2_iter19 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp2_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter2 <= ap_enable_reg_pp2_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp2_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter3 <= ap_enable_reg_pp2_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp2_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter4 <= ap_enable_reg_pp2_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp2_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter5 <= ap_enable_reg_pp2_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp2_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter6 <= ap_enable_reg_pp2_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp2_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter7 <= ap_enable_reg_pp2_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp2_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter8 <= ap_enable_reg_pp2_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp2_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter9 <= ap_enable_reg_pp2_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp3_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp3_stage0_subdone) & (1'b1 == ap_condition_pp3_exit_iter0_state28) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
            ap_enable_reg_pp3_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state27)) begin
            ap_enable_reg_pp3_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp3_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp3_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp3_exit_iter0_state28)) begin
                ap_enable_reg_pp3_iter1 <= (1'b1 ^ ap_condition_pp3_exit_iter0_state28);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp3_iter1 <= ap_enable_reg_pp3_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp3_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp3_stage0_subdone)) begin
            ap_enable_reg_pp3_iter2 <= ap_enable_reg_pp3_iter1;
        end else if ((1'b1 == ap_CS_fsm_state27)) begin
            ap_enable_reg_pp3_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp4_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp4_stage0_subdone) & (1'b1 == ap_CS_fsm_pp4_stage0) & (1'b1 == ap_condition_pp4_exit_iter0_state33))) begin
            ap_enable_reg_pp4_iter0 <= 1'b0;
        end else if (((grp_dataflow_section_fu_458_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state32))) begin
            ap_enable_reg_pp4_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp4_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp4_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp4_exit_iter0_state33)) begin
                ap_enable_reg_pp4_iter1 <= (1'b1 ^ ap_condition_pp4_exit_iter0_state33);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp4_iter1 <= ap_enable_reg_pp4_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp4_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp4_stage0_subdone)) begin
            ap_enable_reg_pp4_iter2 <= ap_enable_reg_pp4_iter1;
        end else if (((grp_dataflow_section_fu_458_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state32))) begin
            ap_enable_reg_pp4_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_dataflow_section_fu_458_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state31)) begin
            grp_dataflow_section_fu_458_ap_start_reg <= 1'b1;
        end else if ((grp_dataflow_section_fu_458_ap_ready == 1'b1)) begin
            grp_dataflow_section_fu_458_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        c_reg_403 <= 5'd0;
    end else if (((1'b0 == ap_block_pp2_stage0_11001) & (icmp_ln16_fu_609_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp2_stage0) & (ap_enable_reg_pp2_iter0 == 1'b1))) begin
        c_reg_403 <= add_ln18_fu_657_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        empty_48_reg_370 <= 11'd0;
    end else if (((exitcond15210_fu_592_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        empty_48_reg_370 <= empty_49_fu_586_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        i_1_reg_425 <= 6'd0;
    end else if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter1 == 1'b1) & (icmp_ln96_reg_957 == 1'd0) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        i_1_reg_425 <= select_ln96_1_reg_966;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dataflow_section_fu_458_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state32))) begin
        i_2_reg_447 <= 4'd0;
    end else if (((1'b0 == ap_block_pp4_stage0_11001) & (icmp_ln40_fu_838_p2 == 1'd0) & (ap_enable_reg_pp4_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage0))) begin
        i_2_reg_447 <= add_ln40_fu_832_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln27_reg_865 == 1'd0))) begin
        i_reg_348 <= select_ln27_1_reg_874;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_reg_348 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        indvar_flatten15_reg_414 <= 11'd0;
    end else if (((1'b0 == ap_block_pp3_stage0_11001) & (icmp_ln96_fu_754_p2 == 1'd0) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        indvar_flatten15_reg_414 <= add_ln96_1_fu_748_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        indvar_flatten7_reg_381 <= 10'd0;
    end else if (((1'b0 == ap_block_pp2_stage0_11001) & (icmp_ln16_fu_609_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp2_stage0) & (ap_enable_reg_pp2_iter0 == 1'b1))) begin
        indvar_flatten7_reg_381 <= add_ln16_2_fu_603_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln27_fu_500_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten_reg_337 <= add_ln27_1_fu_494_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        indvar_flatten_reg_337 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        j_1_reg_436 <= 6'd0;
    end else if (((1'b0 == ap_block_pp3_stage0_11001) & (icmp_ln96_fu_754_p2 == 1'd0) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        j_1_reg_436 <= add_ln98_fu_788_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln27_fu_500_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        j_reg_359 <= add_ln28_fu_538_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        j_reg_359 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        r_reg_392 <= 5'd0;
    end else if (((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter1 == 1'b1) & (icmp_ln16_reg_904 == 1'd0) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        r_reg_392 <= select_ln16_1_reg_914;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (icmp_ln16_fu_609_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        add_ln16_1_reg_921 <= add_ln16_1_fu_651_p2;
        select_ln16_reg_908 <= select_ln16_fu_627_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (icmp_ln16_reg_904 == 1'd0) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        add_ln22_3_reg_937 <= add_ln22_3_fu_738_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp2_stage0_11001)) begin
        add_ln22_3_reg_937_pp2_iter10_reg <= add_ln22_3_reg_937_pp2_iter9_reg;
        add_ln22_3_reg_937_pp2_iter11_reg <= add_ln22_3_reg_937_pp2_iter10_reg;
        add_ln22_3_reg_937_pp2_iter12_reg <= add_ln22_3_reg_937_pp2_iter11_reg;
        add_ln22_3_reg_937_pp2_iter13_reg <= add_ln22_3_reg_937_pp2_iter12_reg;
        add_ln22_3_reg_937_pp2_iter14_reg <= add_ln22_3_reg_937_pp2_iter13_reg;
        add_ln22_3_reg_937_pp2_iter15_reg <= add_ln22_3_reg_937_pp2_iter14_reg;
        add_ln22_3_reg_937_pp2_iter16_reg <= add_ln22_3_reg_937_pp2_iter15_reg;
        add_ln22_3_reg_937_pp2_iter17_reg <= add_ln22_3_reg_937_pp2_iter16_reg;
        add_ln22_3_reg_937_pp2_iter18_reg <= add_ln22_3_reg_937_pp2_iter17_reg;
        add_ln22_3_reg_937_pp2_iter2_reg <= add_ln22_3_reg_937;
        add_ln22_3_reg_937_pp2_iter3_reg <= add_ln22_3_reg_937_pp2_iter2_reg;
        add_ln22_3_reg_937_pp2_iter4_reg <= add_ln22_3_reg_937_pp2_iter3_reg;
        add_ln22_3_reg_937_pp2_iter5_reg <= add_ln22_3_reg_937_pp2_iter4_reg;
        add_ln22_3_reg_937_pp2_iter6_reg <= add_ln22_3_reg_937_pp2_iter5_reg;
        add_ln22_3_reg_937_pp2_iter7_reg <= add_ln22_3_reg_937_pp2_iter6_reg;
        add_ln22_3_reg_937_pp2_iter8_reg <= add_ln22_3_reg_937_pp2_iter7_reg;
        add_ln22_3_reg_937_pp2_iter9_reg <= add_ln22_3_reg_937_pp2_iter8_reg;
        icmp_ln16_reg_904_pp2_iter10_reg <= icmp_ln16_reg_904_pp2_iter9_reg;
        icmp_ln16_reg_904_pp2_iter11_reg <= icmp_ln16_reg_904_pp2_iter10_reg;
        icmp_ln16_reg_904_pp2_iter12_reg <= icmp_ln16_reg_904_pp2_iter11_reg;
        icmp_ln16_reg_904_pp2_iter13_reg <= icmp_ln16_reg_904_pp2_iter12_reg;
        icmp_ln16_reg_904_pp2_iter14_reg <= icmp_ln16_reg_904_pp2_iter13_reg;
        icmp_ln16_reg_904_pp2_iter15_reg <= icmp_ln16_reg_904_pp2_iter14_reg;
        icmp_ln16_reg_904_pp2_iter16_reg <= icmp_ln16_reg_904_pp2_iter15_reg;
        icmp_ln16_reg_904_pp2_iter17_reg <= icmp_ln16_reg_904_pp2_iter16_reg;
        icmp_ln16_reg_904_pp2_iter18_reg <= icmp_ln16_reg_904_pp2_iter17_reg;
        icmp_ln16_reg_904_pp2_iter2_reg <= icmp_ln16_reg_904_pp2_iter1_reg;
        icmp_ln16_reg_904_pp2_iter3_reg <= icmp_ln16_reg_904_pp2_iter2_reg;
        icmp_ln16_reg_904_pp2_iter4_reg <= icmp_ln16_reg_904_pp2_iter3_reg;
        icmp_ln16_reg_904_pp2_iter5_reg <= icmp_ln16_reg_904_pp2_iter4_reg;
        icmp_ln16_reg_904_pp2_iter6_reg <= icmp_ln16_reg_904_pp2_iter5_reg;
        icmp_ln16_reg_904_pp2_iter7_reg <= icmp_ln16_reg_904_pp2_iter6_reg;
        icmp_ln16_reg_904_pp2_iter8_reg <= icmp_ln16_reg_904_pp2_iter7_reg;
        icmp_ln16_reg_904_pp2_iter9_reg <= icmp_ln16_reg_904_pp2_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter18 == 1'b1) & (icmp_ln16_reg_904_pp2_iter17_reg == 1'd0))) begin
        conv4_i_i_reg_947 <= grp_fu_489_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        icmp_ln16_reg_904 <= icmp_ln16_fu_609_p2;
        icmp_ln16_reg_904_pp2_iter1_reg <= icmp_ln16_reg_904;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln27_reg_865 <= icmp_ln27_fu_500_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp4_stage0_11001) & (1'b1 == ap_CS_fsm_pp4_stage0))) begin
        icmp_ln40_reg_995 <= icmp_ln40_fu_838_p2;
        icmp_ln40_reg_995_pp4_iter1_reg <= icmp_ln40_reg_995;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        icmp_ln96_reg_957 <= icmp_ln96_fu_754_p2;
        icmp_ln96_reg_957_pp3_iter1_reg <= icmp_ln96_reg_957;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter2 == 1'b1) & (icmp_ln16_reg_904_pp2_iter1_reg == 1'd0))) begin
        img_buffer_load_reg_942 <= img_buffer_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (icmp_ln16_fu_609_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp2_stage0) & (ap_enable_reg_pp2_iter0 == 1'b1))) begin
        select_ln16_1_reg_914 <= select_ln16_1_fu_635_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln27_fu_500_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        select_ln27_1_reg_874 <= select_ln27_1_fu_526_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln27_fu_500_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        select_ln27_reg_869 <= select_ln27_fu_518_p3;
        temp_in_data_V_reg_881 <= in_stream_TDATA_int_regslice;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (icmp_ln96_fu_754_p2 == 1'd0) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        select_ln96_1_reg_966 <= select_ln96_1_fu_780_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (icmp_ln96_fu_754_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        select_ln96_reg_961 <= select_ln96_fu_772_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp4_stage0_11001) & (icmp_ln40_fu_838_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp4_stage0))) begin
        temp_out_last_V_reg_1004 <= temp_out_last_V_fu_849_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (icmp_ln96_reg_957 == 1'd0) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        zext_ln100_2_reg_978[10 : 0] <= zext_ln100_2_fu_827_p1[10 : 0];
    end
end

always @ (*) begin
    if ((icmp_ln27_fu_500_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln16_fu_609_p2 == 1'd1)) begin
        ap_condition_pp2_exit_iter0_state7 = 1'b1;
    end else begin
        ap_condition_pp2_exit_iter0_state7 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln96_fu_754_p2 == 1'd1)) begin
        ap_condition_pp3_exit_iter0_state28 = 1'b1;
    end else begin
        ap_condition_pp3_exit_iter0_state28 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln40_fu_838_p2 == 1'd1)) begin
        ap_condition_pp4_exit_iter0_state33 = 1'b1;
    end else begin
        ap_condition_pp4_exit_iter0_state33 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state36) & (regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter19 == 1'b0) & (ap_enable_reg_pp2_iter17 == 1'b0) & (ap_enable_reg_pp2_iter16 == 1'b0) & (ap_enable_reg_pp2_iter15 == 1'b0) & (ap_enable_reg_pp2_iter14 == 1'b0) & (ap_enable_reg_pp2_iter13 == 1'b0) & (ap_enable_reg_pp2_iter12 == 1'b0) & (ap_enable_reg_pp2_iter11 == 1'b0) & (ap_enable_reg_pp2_iter10 == 1'b0) & (ap_enable_reg_pp2_iter9 == 1'b0) & (ap_enable_reg_pp2_iter8 == 1'b0) & (ap_enable_reg_pp2_iter7 == 1'b0) & (ap_enable_reg_pp2_iter6 == 1'b0) & (ap_enable_reg_pp2_iter5 == 1'b0) & (ap_enable_reg_pp2_iter4 == 1'b0) & (ap_enable_reg_pp2_iter3 == 1'b0) & (ap_enable_reg_pp2_iter1 == 1'b0) & (ap_enable_reg_pp2_iter18 == 1'b0) & (ap_enable_reg_pp2_iter2 == 1'b0) & (ap_enable_reg_pp2_iter0 == 1'b0))) begin
        ap_idle_pp2 = 1'b1;
    end else begin
        ap_idle_pp2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter2 == 1'b0) & (ap_enable_reg_pp3_iter1 == 1'b0) & (ap_enable_reg_pp3_iter0 == 1'b0))) begin
        ap_idle_pp3 = 1'b1;
    end else begin
        ap_idle_pp3 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp4_iter2 == 1'b0) & (ap_enable_reg_pp4_iter1 == 1'b0) & (ap_enable_reg_pp4_iter0 == 1'b0))) begin
        ap_idle_pp4 = 1'b1;
    end else begin
        ap_idle_pp4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage0) & (ap_enable_reg_pp3_iter1 == 1'b1) & (icmp_ln96_reg_957 == 1'd0) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        ap_phi_mux_i_1_phi_fu_429_p4 = select_ln96_1_reg_966;
    end else begin
        ap_phi_mux_i_1_phi_fu_429_p4 = i_1_reg_425;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln27_reg_865 == 1'd0))) begin
        ap_phi_mux_i_phi_fu_352_p4 = select_ln27_1_reg_874;
    end else begin
        ap_phi_mux_i_phi_fu_352_p4 = i_reg_348;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (icmp_ln16_reg_904 == 1'd0) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        ap_phi_mux_r_phi_fu_396_p4 = select_ln16_1_reg_914;
    end else begin
        ap_phi_mux_r_phi_fu_396_p4 = r_reg_392;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state36) & (regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state32))) begin
        grp_fu_489_ce = grp_dataflow_section_fu_458_grp_fu_489_p_ce;
    end else begin
        grp_fu_489_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state32))) begin
        grp_fu_489_p0 = grp_dataflow_section_fu_458_grp_fu_489_p_din0;
    end else if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter3 == 1'b1))) begin
        grp_fu_489_p0 = img_buffer_load_reg_942;
    end else begin
        grp_fu_489_p0 = img_buffer_load_reg_942;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state32))) begin
        grp_fu_489_p1 = grp_dataflow_section_fu_458_grp_fu_489_p_din1;
    end else if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter3 == 1'b1))) begin
        grp_fu_489_p1 = 32'd1132396544;
    end else begin
        grp_fu_489_p1 = 32'd1132396544;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        img_buffer_address0 = zext_ln22_4_fu_724_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img_buffer_address0 = zext_ln32_2_fu_577_p1;
    end else begin
        img_buffer_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        img_buffer_ce0 = 1'b1;
    end else begin
        img_buffer_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln27_reg_865 == 1'd0))) begin
        img_buffer_we0 = 1'b1;
    end else begin
        img_buffer_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln27_fu_500_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_stream_TDATA_blk_n = in_stream_TVALID_int_regslice;
    end else begin
        in_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln27_fu_500_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_stream_TREADY_int_regslice = 1'b1;
    end else begin
        in_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln40_reg_995_pp4_iter1_reg == 1'd0) & (ap_enable_reg_pp4_iter2 == 1'b1) & (1'b0 == ap_block_pp4_stage0)) | ((icmp_ln40_reg_995 == 1'd0) & (ap_enable_reg_pp4_iter1 == 1'b1) & (1'b0 == ap_block_pp4_stage0) & (1'b1 == ap_CS_fsm_pp4_stage0)))) begin
        out_stream_TDATA_blk_n = out_stream_TREADY_int_regslice;
    end else begin
        out_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln40_reg_995 == 1'd0) & (ap_enable_reg_pp4_iter1 == 1'b1) & (1'b0 == ap_block_pp4_stage0_11001) & (1'b1 == ap_CS_fsm_pp4_stage0))) begin
        out_stream_TVALID_int_regslice = 1'b1;
    end else begin
        out_stream_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp4_stage0) & (ap_enable_reg_pp4_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage0))) begin
        output_buffer_address0 = zext_ln40_fu_844_p1;
    end else if ((1'b1 == ap_CS_fsm_state32)) begin
        output_buffer_address0 = grp_dataflow_section_fu_458_prediction_address0;
    end else begin
        output_buffer_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp4_stage0_11001) & (ap_enable_reg_pp4_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage0))) begin
        output_buffer_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state32)) begin
        output_buffer_ce0 = grp_dataflow_section_fu_458_prediction_ce0;
    end else begin
        output_buffer_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        output_buffer_ce1 = grp_dataflow_section_fu_458_prediction_ce1;
    end else begin
        output_buffer_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        output_buffer_we0 = grp_dataflow_section_fu_458_prediction_we0;
    end else begin
        output_buffer_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage0) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        pad_img0_address0 = zext_ln100_2_fu_827_p1;
    end else if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter19 == 1'b1))) begin
        pad_img0_address0 = zext_ln22_6_fu_744_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        pad_img0_address0 = p_cast_fu_598_p1;
    end else if ((1'b1 == ap_CS_fsm_state32)) begin
        pad_img0_address0 = grp_dataflow_section_fu_458_pad_img0_address0;
    end else begin
        pad_img0_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0)) | ((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter19 == 1'b1)))) begin
        pad_img0_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state32)) begin
        pad_img0_ce0 = grp_dataflow_section_fu_458_pad_img0_ce0;
    end else begin
        pad_img0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        pad_img0_ce1 = grp_dataflow_section_fu_458_pad_img0_ce1;
    end else begin
        pad_img0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter19 == 1'b1))) begin
        pad_img0_d0 = conv4_i_i_reg_947;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        pad_img0_d0 = 32'd0;
    end else begin
        pad_img0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((exitcond15210_fu_592_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)) | ((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter19 == 1'b1) & (icmp_ln16_reg_904_pp2_iter18_reg == 1'd0)))) begin
        pad_img0_we0 = 1'b1;
    end else begin
        pad_img0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage0) & (ap_enable_reg_pp3_iter2 == 1'b1))) begin
        pad_img1_address0 = zext_ln100_2_reg_978;
    end else if ((1'b1 == ap_CS_fsm_state32)) begin
        pad_img1_address0 = grp_dataflow_section_fu_458_pad_img1_address0;
    end else begin
        pad_img1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter2 == 1'b1))) begin
        pad_img1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state32)) begin
        pad_img1_ce0 = grp_dataflow_section_fu_458_pad_img1_ce0;
    end else begin
        pad_img1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        pad_img1_ce1 = grp_dataflow_section_fu_458_pad_img1_ce1;
    end else begin
        pad_img1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter2 == 1'b1) & (icmp_ln96_reg_957_pp3_iter1_reg == 1'd0))) begin
        pad_img1_we0 = 1'b1;
    end else begin
        pad_img1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage0) & (ap_enable_reg_pp3_iter2 == 1'b1))) begin
        pad_img2_address0 = zext_ln100_2_reg_978;
    end else if ((1'b1 == ap_CS_fsm_state32)) begin
        pad_img2_address0 = grp_dataflow_section_fu_458_pad_img2_address0;
    end else begin
        pad_img2_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter2 == 1'b1))) begin
        pad_img2_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state32)) begin
        pad_img2_ce0 = grp_dataflow_section_fu_458_pad_img2_ce0;
    end else begin
        pad_img2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        pad_img2_ce1 = grp_dataflow_section_fu_458_pad_img2_ce1;
    end else begin
        pad_img2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter2 == 1'b1) & (icmp_ln96_reg_957_pp3_iter1_reg == 1'd0))) begin
        pad_img2_we0 = 1'b1;
    end else begin
        pad_img2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage0) & (ap_enable_reg_pp3_iter2 == 1'b1))) begin
        pad_img3_address0 = zext_ln100_2_reg_978;
    end else if ((1'b1 == ap_CS_fsm_state32)) begin
        pad_img3_address0 = grp_dataflow_section_fu_458_pad_img3_address0;
    end else begin
        pad_img3_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter2 == 1'b1))) begin
        pad_img3_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state32)) begin
        pad_img3_ce0 = grp_dataflow_section_fu_458_pad_img3_ce0;
    end else begin
        pad_img3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        pad_img3_ce1 = grp_dataflow_section_fu_458_pad_img3_ce1;
    end else begin
        pad_img3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter2 == 1'b1) & (icmp_ln96_reg_957_pp3_iter1_reg == 1'd0))) begin
        pad_img3_we0 = 1'b1;
    end else begin
        pad_img3_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((icmp_ln27_fu_500_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((icmp_ln27_fu_500_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((exitcond15210_fu_592_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_pp2_stage0;
        end
        ap_ST_fsm_pp2_stage0 : begin
            if ((~((1'b0 == ap_block_pp2_stage0_subdone) & (ap_enable_reg_pp2_iter1 == 1'b0) & (icmp_ln16_fu_609_p2 == 1'd1) & (ap_enable_reg_pp2_iter0 == 1'b1)) & ~((1'b0 == ap_block_pp2_stage0_subdone) & (ap_enable_reg_pp2_iter19 == 1'b1) & (ap_enable_reg_pp2_iter18 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end else if ((((1'b0 == ap_block_pp2_stage0_subdone) & (ap_enable_reg_pp2_iter19 == 1'b1) & (ap_enable_reg_pp2_iter18 == 1'b0)) | ((1'b0 == ap_block_pp2_stage0_subdone) & (ap_enable_reg_pp2_iter1 == 1'b0) & (icmp_ln16_fu_609_p2 == 1'd1) & (ap_enable_reg_pp2_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_pp3_stage0;
        end
        ap_ST_fsm_pp3_stage0 : begin
            if ((~((1'b0 == ap_block_pp3_stage0_subdone) & (ap_enable_reg_pp3_iter1 == 1'b0) & (icmp_ln96_fu_754_p2 == 1'd1) & (ap_enable_reg_pp3_iter0 == 1'b1)) & ~((1'b0 == ap_block_pp3_stage0_subdone) & (ap_enable_reg_pp3_iter2 == 1'b1) & (ap_enable_reg_pp3_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage0;
            end else if ((((1'b0 == ap_block_pp3_stage0_subdone) & (ap_enable_reg_pp3_iter2 == 1'b1) & (ap_enable_reg_pp3_iter1 == 1'b0)) | ((1'b0 == ap_block_pp3_stage0_subdone) & (ap_enable_reg_pp3_iter1 == 1'b0) & (icmp_ln96_fu_754_p2 == 1'd1) & (ap_enable_reg_pp3_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage0;
            end
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            if (((grp_dataflow_section_fu_458_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state32))) begin
                ap_NS_fsm = ap_ST_fsm_pp4_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state32;
            end
        end
        ap_ST_fsm_pp4_stage0 : begin
            if ((~((ap_enable_reg_pp4_iter1 == 1'b0) & (1'b0 == ap_block_pp4_stage0_subdone) & (icmp_ln40_fu_838_p2 == 1'd1) & (ap_enable_reg_pp4_iter0 == 1'b1)) & ~((ap_enable_reg_pp4_iter2 == 1'b1) & (ap_enable_reg_pp4_iter1 == 1'b0) & (1'b0 == ap_block_pp4_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_pp4_stage0;
            end else if ((((ap_enable_reg_pp4_iter2 == 1'b1) & (ap_enable_reg_pp4_iter1 == 1'b0) & (1'b0 == ap_block_pp4_stage0_subdone)) | ((ap_enable_reg_pp4_iter1 == 1'b0) & (1'b0 == ap_block_pp4_stage0_subdone) & (icmp_ln40_fu_838_p2 == 1'd1) & (ap_enable_reg_pp4_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state36;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp4_stage0;
            end
        end
        ap_ST_fsm_state36 : begin
            if (((1'b1 == ap_CS_fsm_state36) & (regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state36;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln100_1_fu_821_p2 = (add_ln100_fu_812_p2 + zext_ln100_1_fu_818_p1);

assign add_ln100_fu_812_p2 = (tmp_69_fu_794_p3 + zext_ln100_fu_808_p1);

assign add_ln16_1_fu_651_p2 = (ap_phi_mux_r_phi_fu_396_p4 + select_ln16_2_fu_643_p3);

assign add_ln16_2_fu_603_p2 = (indvar_flatten7_reg_381 + 10'd1);

assign add_ln16_fu_615_p2 = (ap_phi_mux_r_phi_fu_396_p4 + 5'd1);

assign add_ln18_fu_657_p2 = (select_ln16_fu_627_p3 + 5'd1);

assign add_ln22_1_fu_709_p2 = (zext_ln22_1_fu_694_p1 + zext_ln22_2_fu_705_p1);

assign add_ln22_2_fu_718_p2 = (sub_ln22_fu_681_p2 + zext_ln22_3_fu_715_p1);

assign add_ln22_3_fu_738_p2 = (add_ln22_1_fu_709_p2 + zext_ln22_5_fu_734_p1);

assign add_ln22_fu_729_p2 = (select_ln16_reg_908 + 5'd3);

assign add_ln27_1_fu_494_p2 = (indvar_flatten_reg_337 + 10'd1);

assign add_ln27_fu_506_p2 = (ap_phi_mux_i_phi_fu_352_p4 + 5'd1);

assign add_ln28_fu_538_p2 = (select_ln27_fu_518_p3 + 5'd1);

assign add_ln32_fu_571_p2 = (sub_ln32_fu_562_p2 + zext_ln32_1_fu_568_p1);

assign add_ln40_fu_832_p2 = (i_2_reg_447 + 4'd1);

assign add_ln96_1_fu_748_p2 = (indvar_flatten15_reg_414 + 11'd1);

assign add_ln96_fu_760_p2 = (ap_phi_mux_i_1_phi_fu_429_p4 + 6'd1);

assign add_ln98_fu_788_p2 = (select_ln96_fu_772_p3 + 6'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp2_stage0 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp3_stage0 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_pp4_stage0 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state36 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd4];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((icmp_ln27_fu_500_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (in_stream_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((icmp_ln27_fu_500_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (in_stream_TVALID_int_regslice == 1'b0));
end

assign ap_block_pp2_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp3_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp3_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp3_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp4_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp4_stage0_01001 = (((icmp_ln40_reg_995_pp4_iter1_reg == 1'd0) & (ap_enable_reg_pp4_iter2 == 1'b1) & (out_stream_TREADY_int_regslice == 1'b0)) | ((icmp_ln40_reg_995 == 1'd0) & (ap_enable_reg_pp4_iter1 == 1'b1) & (out_stream_TREADY_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_pp4_stage0_11001 = (((ap_enable_reg_pp4_iter2 == 1'b1) & ((1'b1 == ap_block_state35_io) | ((icmp_ln40_reg_995_pp4_iter1_reg == 1'd0) & (out_stream_TREADY_int_regslice == 1'b0)))) | ((ap_enable_reg_pp4_iter1 == 1'b1) & ((1'b1 == ap_block_state34_io) | ((icmp_ln40_reg_995 == 1'd0) & (out_stream_TREADY_int_regslice == 1'b0)))));
end

always @ (*) begin
    ap_block_pp4_stage0_subdone = (((ap_enable_reg_pp4_iter2 == 1'b1) & ((1'b1 == ap_block_state35_io) | ((icmp_ln40_reg_995_pp4_iter1_reg == 1'd0) & (out_stream_TREADY_int_regslice == 1'b0)))) | ((ap_enable_reg_pp4_iter1 == 1'b1) & ((1'b1 == ap_block_state34_io) | ((icmp_ln40_reg_995 == 1'd0) & (out_stream_TREADY_int_regslice == 1'b0)))));
end

assign ap_block_state10_pp2_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp2_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp2_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp2_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp2_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp2_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp2_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp2_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp2_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp2_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp2_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp2_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp2_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp2_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp2_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp2_stage0_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp2_stage0_iter19 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp3_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp3_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter0 = ((icmp_ln27_fu_500_p2 == 1'd0) & (in_stream_TVALID_int_regslice == 1'b0));
end

assign ap_block_state30_pp3_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state33_pp4_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state34_io = ((icmp_ln40_reg_995 == 1'd0) & (out_stream_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state34_pp4_stage0_iter1 = ((icmp_ln40_reg_995 == 1'd0) & (out_stream_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state35_io = ((icmp_ln40_reg_995_pp4_iter1_reg == 1'd0) & (out_stream_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state35_pp4_stage0_iter2 = ((icmp_ln40_reg_995_pp4_iter1_reg == 1'd0) & (out_stream_TREADY_int_regslice == 1'b0));
end

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp2_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp2_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp2_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_pp2 = (ap_idle_pp2 ^ 1'b1);

assign ap_enable_pp3 = (ap_idle_pp3 ^ 1'b1);

assign ap_enable_pp4 = (ap_idle_pp4 ^ 1'b1);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign empty_49_fu_586_p2 = (empty_48_reg_370 + 11'd1);

assign exitcond15210_fu_592_p2 = ((empty_48_reg_370 == 11'd1156) ? 1'b1 : 1'b0);

assign grp_dataflow_section_fu_458_ap_start = grp_dataflow_section_fu_458_ap_start_reg;

assign grp_dataflow_section_fu_458_grp_fu_489_p_dout0 = grp_fu_489_p2;

assign icmp_ln16_fu_609_p2 = ((indvar_flatten7_reg_381 == 10'd784) ? 1'b1 : 1'b0);

assign icmp_ln18_fu_621_p2 = ((c_reg_403 == 5'd28) ? 1'b1 : 1'b0);

assign icmp_ln27_fu_500_p2 = ((indvar_flatten_reg_337 == 10'd784) ? 1'b1 : 1'b0);

assign icmp_ln2826_fu_512_p2 = ((j_reg_359 == 5'd28) ? 1'b1 : 1'b0);

assign icmp_ln40_fu_838_p2 = ((i_2_reg_447 == 4'd10) ? 1'b1 : 1'b0);

assign icmp_ln96_fu_754_p2 = ((indvar_flatten15_reg_414 == 11'd1156) ? 1'b1 : 1'b0);

assign icmp_ln98_fu_766_p2 = ((j_1_reg_436 == 6'd34) ? 1'b1 : 1'b0);

assign img_buffer_d0 = temp_in_data_V_reg_881;

assign in_stream_TREADY = regslice_both_in_stream_V_data_V_U_ack_in;

assign out_stream_TDATA_int_regslice = output_buffer_q0;

assign out_stream_TVALID = regslice_both_out_stream_V_data_V_U_vld_out;

assign p_cast_fu_598_p1 = empty_48_reg_370;

assign select_ln16_1_fu_635_p3 = ((icmp_ln18_fu_621_p2[0:0] == 1'b1) ? add_ln16_fu_615_p2 : ap_phi_mux_r_phi_fu_396_p4);

assign select_ln16_2_fu_643_p3 = ((icmp_ln18_fu_621_p2[0:0] == 1'b1) ? 5'd4 : 5'd3);

assign select_ln16_fu_627_p3 = ((icmp_ln18_fu_621_p2[0:0] == 1'b1) ? 5'd0 : c_reg_403);

assign select_ln27_1_fu_526_p3 = ((icmp_ln2826_fu_512_p2[0:0] == 1'b1) ? add_ln27_fu_506_p2 : ap_phi_mux_i_phi_fu_352_p4);

assign select_ln27_fu_518_p3 = ((icmp_ln2826_fu_512_p2[0:0] == 1'b1) ? 5'd0 : j_reg_359);

assign select_ln96_1_fu_780_p3 = ((icmp_ln98_fu_766_p2[0:0] == 1'b1) ? add_ln96_fu_760_p2 : ap_phi_mux_i_1_phi_fu_429_p4);

assign select_ln96_fu_772_p3 = ((icmp_ln98_fu_766_p2[0:0] == 1'b1) ? 6'd0 : j_1_reg_436);

assign sub_ln22_fu_681_p2 = (tmp_65_fu_663_p3 - zext_ln22_fu_677_p1);

assign sub_ln32_fu_562_p2 = (tmp_fu_544_p3 - zext_ln32_fu_558_p1);

assign temp_out_last_V_fu_849_p2 = ((i_2_reg_447 == 4'd9) ? 1'b1 : 1'b0);

assign tmp_65_fu_663_p3 = {{select_ln16_1_reg_914}, {5'd0}};

assign tmp_66_fu_670_p3 = {{select_ln16_1_reg_914}, {2'd0}};

assign tmp_67_fu_687_p3 = {{add_ln16_1_reg_921}, {5'd0}};

assign tmp_68_fu_698_p3 = {{add_ln16_1_reg_921}, {1'd0}};

assign tmp_69_fu_794_p3 = {{select_ln96_1_reg_966}, {5'd0}};

assign tmp_70_fu_801_p3 = {{select_ln96_1_reg_966}, {1'd0}};

assign tmp_fu_544_p3 = {{select_ln27_1_reg_874}, {5'd0}};

assign tmp_s_fu_551_p3 = {{select_ln27_1_reg_874}, {2'd0}};

assign zext_ln100_1_fu_818_p1 = select_ln96_reg_961;

assign zext_ln100_2_fu_827_p1 = add_ln100_1_fu_821_p2;

assign zext_ln100_fu_808_p1 = tmp_70_fu_801_p3;

assign zext_ln22_1_fu_694_p1 = tmp_67_fu_687_p3;

assign zext_ln22_2_fu_705_p1 = tmp_68_fu_698_p3;

assign zext_ln22_3_fu_715_p1 = select_ln16_reg_908;

assign zext_ln22_4_fu_724_p1 = add_ln22_2_fu_718_p2;

assign zext_ln22_5_fu_734_p1 = add_ln22_fu_729_p2;

assign zext_ln22_6_fu_744_p1 = add_ln22_3_reg_937_pp2_iter18_reg;

assign zext_ln22_fu_677_p1 = tmp_66_fu_670_p3;

assign zext_ln32_1_fu_568_p1 = select_ln27_reg_869;

assign zext_ln32_2_fu_577_p1 = add_ln32_fu_571_p2;

assign zext_ln32_fu_558_p1 = tmp_s_fu_551_p3;

assign zext_ln40_fu_844_p1 = i_2_reg_447;

always @ (posedge ap_clk) begin
    zext_ln100_2_reg_978[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
end

endmodule //cnn_stream_accel
